import { describe, expect, it } from "vitest";
import {
  assertProviderNeutralCustomerText,
  createCompatibleChatTextGateway,
  createGen1LiveVoiceProviderGateway,
  createHttpTextProviderGateway,
  createOpenAIRealtimeVoiceGateway,
  createOpenAIResponsesGateway,
  LiveVoiceGatewayError,
  ProviderGatewayError,
  type LiveVoiceEvent,
  type RestrictedLiveSocket,
} from "./index";

const request = {
  correlationId: "turn-1", locale: "en" as const, systemPolicy: "policy", messages: [],
  customerMessage: "Hello", structuredOutputSchemaVersion: "sales-core.v1" as const,
};

describe("internal text gateway", () => {
  it("normalizes a valid result without routing metadata", async () => {
    const gateway = createHttpTextProviderGateway({
      endpoint: "https://ai-gateway.internal/generate", serviceToken: "secret",
      fetchImpl: async (_input, init) => {
        expect(JSON.parse(String(init?.body))).toMatchObject({ capability: "sales_text", customerMessage: "Hello" });
        return new Response(JSON.stringify({ output: { ok: true }, nativeUsage: { inputUnits: 12, outputUnits: 8 } }), { status: 200 });
      },
    });
    await expect(gateway.generate(request)).resolves.toEqual({ output: { ok: true }, nativeUsage: { inputUnits: 12, outputUnits: 8 } });
  });

  it("routes translation requests through the same owner-selected gateway", async () => {
    const gateway = createHttpTextProviderGateway({
      endpoint: "https://ai-gateway.internal/generate", serviceToken: "secret",
      fetchImpl: async (_input, init) => {
        expect(JSON.parse(String(init?.body))).toMatchObject({ capability: "translation", structuredOutputSchemaVersion: "translation.v1" });
        return new Response(JSON.stringify({ output: { translations: ["จองคำปรึกษา"] }, nativeUsage: { inputUnits: 4, outputUnits: 3 } }), { status: 200 });
      },
    });
    await expect(gateway.generate({ ...request, structuredOutputSchemaVersion: "translation.v1" })).resolves.toMatchObject({ output: { translations: ["จองคำปรึกษา"] } });
  });

  it("returns only a stable safe error for upstream failures", async () => {
    const gateway = createHttpTextProviderGateway({
      endpoint: "https://ai-gateway.internal/generate", serviceToken: "secret",
      fetchImpl: async () => new Response("sensitive upstream body", { status: 503 }),
    });
    await expect(gateway.generate(request)).rejects.toEqual(new ProviderGatewayError("gateway_unavailable"));
  });

  it("bounds a stalled upstream call and collapses it to a safe timeout", async () => {
    const gateway = createHttpTextProviderGateway({
      endpoint: "https://ai-gateway.internal/generate", serviceToken: "secret", timeoutMs: 5,
      fetchImpl: async (_input, init) => new Promise<Response>((_resolve, reject) => {
        init?.signal?.addEventListener("abort", () => reject(init.signal?.reason), { once: true });
      }),
    });
    await expect(gateway.generate(request)).rejects.toEqual(new ProviderGatewayError("gateway_timeout"));
  });

  it("rejects restricted routing identity in customer text", () => {
    expect(() => assertProviderNeutralCustomerText("This reply names GPT-5.")).toThrow(/gateway_invalid_response/);
  });
});

describe("restricted OpenAI Responses gateway", () => {
  it("maps a completed structured response and native usage", async () => {
    const gateway = createOpenAIResponsesGateway({
      apiKey: "sk-restricted-abcdefghijklmnopqrstuvwxyz", model: "restricted-text-route",
      fetchImpl: async (input, init) => {
        expect(String(input)).toBe("https://api.openai.com/v1/responses");
        expect(init?.headers).toMatchObject({
          Authorization: "Bearer sk-restricted-abcdefghijklmnopqrstuvwxyz",
          "Idempotency-Key": "turn-1",
        });
        expect(JSON.parse(String(init?.body))).toMatchObject({
          model: "restricted-text-route", store: false,
          text: { format: { type: "json_object" } },
        });
        return new Response(JSON.stringify({
          status: "completed",
          output: [{ type: "message", content: [{ type: "output_text", text: JSON.stringify({ response: "Hello" }) }] }],
          usage: { input_tokens: 14, output_tokens: 9, input_tokens_details: { cached_tokens: 3 } },
        }), { status: 200 });
      },
    });
    await expect(gateway.generate(request)).resolves.toEqual({
      output: { response: "Hello" },
      nativeUsage: { inputUnits: 14, outputUnits: 9, cachedUnits: 3 },
    });
  });

  it("fails closed on malformed or provider-revealing output", async () => {
    const gateway = createOpenAIResponsesGateway({
      apiKey: "sk-restricted-abcdefghijklmnopqrstuvwxyz", model: "restricted-text-route",
      fetchImpl: async () => new Response(JSON.stringify({
        status: "completed",
        output: [{ type: "message", content: [{ type: "output_text", text: JSON.stringify({ response: "Generated by GPT-5" }) }] }],
        usage: { input_tokens: 1, output_tokens: 1 },
      }), { status: 200 }),
    });
    await expect(gateway.generate(request)).rejects.toEqual(new ProviderGatewayError("gateway_invalid_response"));
  });
});

describe("restricted compatible Chat Completions gateway", () => {
  it.each([
    "https://api.x.ai/v1/chat/completions",
    "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
  ])("normalizes structured output and usage for %s", async (endpoint) => {
    const gateway = createCompatibleChatTextGateway({
      apiKey: "restricted-provider-key-abcdefghijklmnopqrstuvwxyz",
      model: "owner-selected-route",
      endpoint,
      fetchImpl: async (input, init) => {
        expect(String(input)).toBe(endpoint);
        expect(JSON.parse(String(init?.body))).toMatchObject({
          model: "owner-selected-route",
          messages: [
            { role: "system", content: "policy" },
            { role: "user", content: "Hello" },
          ],
          response_format: { type: "json_object" },
        });
        return new Response(JSON.stringify({
          choices: [{ message: { content: JSON.stringify({ response: "Hello" }) } }],
          usage: { prompt_tokens: 11, completion_tokens: 7, prompt_tokens_details: { cached_tokens: 2 } },
        }), { status: 200 });
      },
    });
    await expect(gateway.generate(request)).resolves.toEqual({
      output: { response: "Hello" },
      nativeUsage: { inputUnits: 11, outputUnits: 7, cachedUnits: 2 },
    });
  });

  it("sends the authoritative structured-output schema when supplied", async () => {
    const structuredOutputJsonSchema = {
      type: "object", properties: { schemaVersion: { const: "sales-core.v1" } }, required: ["schemaVersion"],
    };
    const gateway = createCompatibleChatTextGateway({
      apiKey: "restricted-provider-key-abcdefghijklmnopqrstuvwxyz",
      model: "owner-selected-route",
      endpoint: "https://api.x.ai/v1/chat/completions",
      fetchImpl: async (_input, init) => {
        expect(JSON.parse(String(init?.body))).toMatchObject({
          response_format: {
            type: "json_schema",
            json_schema: { name: "sales_core_v1", strict: true, schema: structuredOutputJsonSchema },
          },
        });
        return new Response(JSON.stringify({
          choices: [{ message: { content: JSON.stringify({ schemaVersion: "sales-core.v1" }) } }],
          usage: { prompt_tokens: 1, completion_tokens: 1 },
        }), { status: 200 });
      },
    });
    await expect(gateway.generate({ ...request, structuredOutputJsonSchema })).resolves.toMatchObject({
      output: { schemaVersion: "sales-core.v1" },
    });
  });

  it("fails closed on malformed or provider-revealing output", async () => {
    const gateway = createCompatibleChatTextGateway({
      apiKey: "restricted-provider-key-abcdefghijklmnopqrstuvwxyz",
      model: "owner-selected-route",
      endpoint: "https://api.x.ai/v1/chat/completions",
      fetchImpl: async () => new Response(JSON.stringify({
        choices: [{ message: { content: JSON.stringify({ response: "Powered by Grok" }) } }],
        usage: { prompt_tokens: 1, completion_tokens: 1 },
      }), { status: 200 }),
    });
    await expect(gateway.generate(request)).rejects.toEqual(new ProviderGatewayError("gateway_invalid_response"));
  });
});

class FakeLiveSocket implements RestrictedLiveSocket {
  readyState = 0;
  sent: string[] = [];
  onopen: (() => void) | null = null;
  onmessage: ((event: Readonly<{ data: unknown }>) => void) | null = null;
  onerror: (() => void) | null = null;
  onclose: (() => void) | null = null;
  send(data: string) { this.sent.push(data); }
  close() { this.readyState = 3; }
  open() { this.readyState = 1; this.onopen?.(); }
  message(value: unknown) { this.onmessage?.({ data: JSON.stringify(value) }); }
  error() { this.onerror?.(); }
  shutdown() { this.readyState = 3; this.onclose?.(); }
}

describe("restricted realtime Voice gateway", () => {
  it("owns setup, raw PCM transport, transcripts, multi-part audio and tool calls", async () => {
    const socket = new FakeLiveSocket(); const events: LiveVoiceEvent[] = [];
    const gateway = createGen1LiveVoiceProviderGateway({
      apiKey: "restricted-key-abcdefghijklmnopqrstuvwxyz", model: "restricted-model",
      voiceName: "restricted-voice", socketFactory: () => socket,
    });
    const connecting = gateway.connect({
      correlationId: "voice-session-1", locale: "en", systemPolicy: "Restricted system policy",
      tools: [{ name: "plan_sales_turn", description: "Plan one turn", parameters: { type: "object" } }],
    }, (event) => { events.push(event); });
    socket.open();
    const setup = JSON.parse(socket.sent[0]!) as Record<string, any>;
    expect(setup.setup.generationConfig.responseModalities).toEqual(["AUDIO"]);
    expect(setup.setup.inputAudioTranscription).toEqual({});
    expect(setup.setup.tools[0].functionDeclarations[0].name).toBe("plan_sales_turn");
    socket.message({ setupComplete: {} });
    const session = await connecting;
    session.sendAudio("AQID"); session.sendActivity("start"); session.sendActivity("end");
    expect(socket.sent.slice(-3).map((value) => JSON.parse(value))).toEqual([
      { realtimeInput: { audio: { mimeType: "audio/pcm;rate=16000", data: "AQID" } } },
      { realtimeInput: { activityStart: {} } }, { realtimeInput: { activityEnd: {} } },
    ]);
    socket.message({ serverContent: {
      inputTranscription: { text: "Hello" }, outputTranscription: { text: "Hi" },
      modelTurn: { parts: [
        { inlineData: { mimeType: "audio/pcm;rate=24000", data: "BAUG" } },
        { inlineData: { mimeType: "audio/pcm;rate=24000", data: "BwgJ" } },
      ] }, turnComplete: true,
    } });
    socket.message({ toolCall: { functionCalls: [{ id: "call-1", name: "plan_sales_turn", args: { customerMessage: "Hello" } }] } });
    expect(events).toEqual([
      { type: "transcript.delta", speaker: "customer", text: "Hello" },
      { type: "transcript.delta", speaker: "agent", text: "Hi" },
      { type: "assistant.speech.started" },
      { type: "audio.chunk", sequence: 0, audioBase64: "BAUG" },
      { type: "audio.chunk", sequence: 1, audioBase64: "BwgJ" },
      { type: "assistant.speech.ended" },
      { type: "tool.call", callId: "call-1", name: "plan_sales_turn", args: { customerMessage: "Hello" } },
    ]);
    session.sendToolResponse({ callId: "call-1", name: "plan_sales_turn", response: { response: "Approved" } });
    expect(JSON.parse(socket.sent.at(-1)!)).toEqual({
      toolResponse: { functionResponses: [{ id: "call-1", name: "plan_sales_turn", response: { response: "Approved" } }] },
    });
  });

  it("fails closed with stable errors when setup is invalid", async () => {
    const socket = new FakeLiveSocket();
    const gateway = createGen1LiveVoiceProviderGateway({
      apiKey: "restricted-key-abcdefghijklmnopqrstuvwxyz", model: "restricted-model",
      voiceName: "restricted-voice", socketFactory: () => socket,
    });
    const connecting = gateway.connect({
      correlationId: "voice-session-2", locale: "th", systemPolicy: "Restricted system policy",
    }, () => undefined);
    socket.open(); socket.onmessage?.({ data: "not-json" });
    await expect(connecting).rejects.toEqual(new LiveVoiceGatewayError("gateway_invalid_response"));
    expect(socket.readyState).toBe(3);
  });

  it("bounds setup stalls and normalizes outages before and after admission", async () => {
    const stalled = new FakeLiveSocket();
    const stalledGateway = createGen1LiveVoiceProviderGateway({
      apiKey: "restricted-key-abcdefghijklmnopqrstuvwxyz", model: "restricted-model",
      voiceName: "restricted-voice", socketFactory: () => stalled, connectTimeoutMs: 5,
    });
    await expect(stalledGateway.connect({
      correlationId: "voice-timeout", locale: "en", systemPolicy: "Restricted system policy",
    }, () => undefined)).rejects.toEqual(new LiveVoiceGatewayError("gateway_timeout"));
    expect(stalled.readyState).toBe(3);

    const unavailable = new FakeLiveSocket();
    const unavailableGateway = createGen1LiveVoiceProviderGateway({
      apiKey: "restricted-key-abcdefghijklmnopqrstuvwxyz", model: "restricted-model",
      voiceName: "restricted-voice", socketFactory: () => unavailable,
    });
    const connecting = unavailableGateway.connect({
      correlationId: "voice-unavailable", locale: "en", systemPolicy: "Restricted system policy",
    }, () => undefined);
    unavailable.open(); unavailable.error();
    await expect(connecting).rejects.toEqual(new LiveVoiceGatewayError("gateway_unavailable"));

    const admitted = new FakeLiveSocket(); const events: LiveVoiceEvent[] = [];
    const admittedGateway = createGen1LiveVoiceProviderGateway({
      apiKey: "restricted-key-abcdefghijklmnopqrstuvwxyz", model: "restricted-model",
      voiceName: "restricted-voice", socketFactory: () => admitted,
    });
    const admission = admittedGateway.connect({
      correlationId: "voice-admitted", locale: "en", systemPolicy: "Restricted system policy",
    }, (event) => { events.push(event); });
    admitted.open(); admitted.message({ setupComplete: {} }); await admission; admitted.shutdown();
    expect(events).toEqual([{ type: "error", code: "upstream_unavailable" }]);
  });
});

describe("restricted OpenAI Realtime gateway", () => {
  it("translates session, PCM audio, transcripts, and tool calls", async () => {
    const socket = new FakeLiveSocket();
    const events: LiveVoiceEvent[] = [];
    const gateway = createOpenAIRealtimeVoiceGateway({
      apiKey: "sk-restricted-abcdefghijklmnopqrstuvwxyz", model: "restricted-realtime-route",
      voiceName: "restricted-voice",
      socketFactory: (url, headers) => {
        expect(url).toContain("wss://api.openai.com/v1/realtime?model=restricted-realtime-route");
        expect(headers.Authorization).toBe("Bearer sk-restricted-abcdefghijklmnopqrstuvwxyz");
        return socket;
      },
    });
    const connecting = gateway.connect({
      correlationId: "voice-openai-1", locale: "en", systemPolicy: "Restricted policy",
      tools: [{ name: "plan_sales_turn", description: "Plan one turn", parameters: { type: "object" } }],
    }, (event) => { events.push(event); });
    socket.open();
    expect(JSON.parse(socket.sent[0]!)).toMatchObject({
      type: "session.update",
      session: {
        model: "restricted-realtime-route", modalities: ["audio"],
        audio: { input: { format: { type: "audio/pcm", rate: 16000 } } },
        tools: [{ type: "function", name: "plan_sales_turn" }],
      },
    });
    socket.message({ type: "session.updated", session: { id: "sess_restricted" } });
    const session = await connecting;
    session.sendAudio("AQID");
    expect(JSON.parse(socket.sent.at(-1)!)).toEqual({ type: "input_audio_buffer.append", audio: "AQID" });
    socket.message({ type: "response.output_audio.delta", delta: "BAUG" });
    socket.message({ type: "response.output_audio_transcript.delta", delta: "Hello" });
    socket.message({ type: "conversation.item.input_audio_transcription.delta", delta: "Hi" });
    socket.message({ type: "response.function_call_arguments.delta", call_id: "call-1", name: "plan_sales_turn", delta: "{\"customer" });
    socket.message({ type: "response.function_call_arguments.done", call_id: "call-1", name: "plan_sales_turn", arguments: "{\"customerMessage\":\"Hi\"}" });
    socket.message({ type: "response.done" });
    expect(events).toEqual([
      { type: "assistant.speech.started" },
      { type: "audio.chunk", sequence: 0, audioBase64: "BAUG" },
      { type: "transcript.delta", speaker: "agent", text: "Hello" },
      { type: "transcript.delta", speaker: "customer", text: "Hi" },
      { type: "tool.call", callId: "call-1", name: "plan_sales_turn", args: { customerMessage: "Hi" } },
      { type: "assistant.speech.ended" },
    ]);
    session.sendToolResponse({ callId: "call-1", name: "plan_sales_turn", response: { customerResponse: "Hello" } });
    expect(socket.sent.slice(-2).map((value) => JSON.parse(value))).toEqual([
      { type: "conversation.item.create", item: {
        type: "function_call_output", call_id: "call-1", output: JSON.stringify({ customerResponse: "Hello" }),
      } },
      { type: "response.create" },
    ]);
  });
});
