/** Thai-first presentation copy shared by the web applications. Product names and
 * protocol terms stay in English when that is how Thai operators recognize them. */
const thaiUi: Readonly<Record<string, string>> = {
  "Try again": "ลองใหม่", "Name": "ชื่อ", "Reject": "ปฏิเสธ", "Thai": "ไทย", "Business name": "ชื่อธุรกิจ",
  "Language": "ภาษา", "Sign in": "เข้าสู่ระบบ", "Create workspace": "สร้างเวิร์กสเปซ", "Leads": "ผู้สนใจ",
  "Request review": "ส่งให้ตรวจสอบ", "Revoke": "เพิกถอน", "Version": "เวอร์ชัน", "Approve": "อนุมัติ",
  "Checked": "ตรวจแล้ว", "failed": "ล้มเหลว", "Investigate": "ตรวจสอบ", "Password": "รหัสผ่าน",
  "Sessions": "เซสชัน", "Timezone": "เขตเวลา", "Action needed:": "ต้องดำเนินการ:", "Attention": "ต้องตรวจสอบ",
  "Authenticator code": "รหัสจากแอปยืนยันตัวตน", "Completed": "เสร็จสิ้น", "Connection name": "ชื่อการเชื่อมต่อ",
  "Email": "อีเมล", "English greeting": "คำทักทายภาษาอังกฤษ", "Thai greeting": "คำทักทายภาษาไทย",
  "Key": "กุญแจ", "Knowledge": "คลังความรู้", "Last checked": "ตรวจล่าสุด", "Matched": "ตรงกัน",
  "Page not found": "ไม่พบหน้า", "pending": "รอดำเนินการ", "Platform Master": "ระบบจัดการแพลตฟอร์ม",
  "Platform operations": "การดำเนินงานแพลตฟอร์ม", "Products": "ผลิตภัณฑ์", "Remove": "นำออก",
  "Retry retrieval": "โหลดใหม่", "Security": "ความปลอดภัย", "Service status": "สถานะบริการ",
  "Team": "ทีมงาน", "Temporarily unavailable": "ไม่พร้อมใช้งานชั่วคราว", "Work email": "อีเมลที่ใช้ทำงาน",
  "Account recovery": "กู้คืนบัญชี", "Account security": "ความปลอดภัยของบัญชี", "Active sessions": "เซสชันที่ใช้งานอยู่",
  "Add recipient": "เพิ่มผู้รับ", "AI Chat": "แชต AI", "Already registered?": "มีบัญชีแล้ว?",
  "Appointment requests": "คำขอนัดหมาย", "Channel": "ช่องทาง", "Close": "ปิด", "Confirm password": "ยืนยันรหัสผ่าน",
  "Contact": "ข้อมูลติดต่อ", "Contacts": "ข้อมูลติดต่อ", "Continue to sign in": "ไปหน้าเข้าสู่ระบบ",
  "Conversations": "การสนทนา", "Current period": "รอบปัจจุบัน", "Customer": "ลูกค้า",
  "Data controls": "การจัดการข้อมูล", "Date": "วันที่", "days": "วัน", "Default language": "ภาษาเริ่มต้น",
  "Description": "คำอธิบาย", "Export CSV": "ส่งออก CSV", "Handovers": "การส่งต่อให้ทีม", "Inbox": "กล่องข้อความ",
  "Manage billing": "จัดการการเรียกเก็บเงิน", "Maximum call seconds": "ระยะเวลาสายสูงสุด (วินาที)",
  "Mode": "โหมด", "Next action": "ขั้นตอนถัดไป", "No": "ไม่", "Operational reason": "เหตุผลในการดำเนินการ",
  "Pipeline": "ขั้นตอนงานขาย", "Product": "ผลิตภัณฑ์", "Publish immutable version": "เผยแพร่เวอร์ชันถาวร",
  "Qualify": "คัดกรอง", "Request": "ส่งคำขอ", "Restricted": "จำกัดสิทธิ์", "Rollback": "ย้อนกลับเวอร์ชัน",
  "Safety cap": "ขีดจำกัดความปลอดภัย", "Sales goal": "เป้าหมายการขาย", "Save draft": "บันทึกฉบับร่าง",
  "Service": "บริการ", "Services & add-ons": "บริการและส่วนเสริม", "Sign in to continue": "เข้าสู่ระบบเพื่อดำเนินการต่อ",
  "Sign out": "ออกจากระบบ", "Tone": "โทนการสนทนา", "Type": "ประเภท", "Updated": "อัปเดตแล้ว",
  "Website": "เว็บไซต์", "Workspace registration": "ลงทะเบียนเวิร์กสเปซ", "Yes": "ใช่", "Your name": "ชื่อของคุณ",
  "Access": "สิทธิ์ใช้งาน", "Account": "บัญชี", "Action": "การดำเนินการ", "Actions": "การดำเนินการ",
  "Activate": "เปิดใช้งาน", "Active": "ใช้งานอยู่", "Add approved text": "เพิ่มข้อความที่อนุมัติแล้ว",
  "Add availability": "เพิ่มเวลาที่พร้อมให้บริการ", "Add customer action": "เพิ่มการดำเนินการสำหรับลูกค้า",
  "Add flow node": "เพิ่มโนดในโฟลว์", "Add text": "เพิ่มข้อความ", "Agent": "เอเจนต์", "Agent name": "ชื่อเอเจนต์",
  "Agents": "เอเจนต์", "AI Chat analytics": "ข้อมูลวิเคราะห์แชต AI", "AI Chat operations": "การดำเนินงานแชต AI",
  "AI Text Bot": "บอตข้อความ AI", "AI Voice Bot": "บอตเสียง AI", "Allowed website origin": "ต้นทางเว็บไซต์ที่อนุญาต",
  "Answers": "คำตอบ", "Appointment request": "คำขอนัดหมาย", "Approve credit review": "อนุมัติการตรวจสอบเครดิต",
  "Approved claims": "ข้อความอ้างอิงที่อนุมัติ", "Approved copy": "ข้อความที่อนุมัติ", "Approved knowledge": "ความรู้ที่อนุมัติ",
  "As of": "ข้อมูล ณ", "Assistant name": "ชื่อผู้ช่วย", "Attempt": "ครั้งที่ลอง", "Automatic": "อัตโนมัติ",
  "Available now": "พร้อมใช้งานแล้ว", "Available products": "ผลิตภัณฑ์ที่พร้อมใช้งาน", "Awaiting customer": "รอลูกค้า",
  "Awaiting review": "รอตรวจสอบ", "Back to Overview": "กลับไปหน้าภาพรวม", "Benefits": "ประโยชน์",
  "Billing": "การเรียกเก็บเงิน", "Billing documents": "เอกสารการเรียกเก็บเงิน", "Billing status": "สถานะการเรียกเก็บเงิน",
  "Book": "จอง", "Bot": "บอต", "Bots": "บอต", "Business account": "บัญชีธุรกิจ", "Business hours": "เวลาทำการ",
  "Business profile": "โปรไฟล์ธุรกิจ", "Call usage": "การใช้งานสาย", "Callback": "ติดต่อกลับ", "Cancel": "ยกเลิก",
  "Cancelled": "ยกเลิกแล้ว", "Captured": "เก็บข้อมูลแล้ว", "Channels": "ช่องทาง", "Check health": "ตรวจสถานะ",
  "Check service status": "ตรวจสถานะบริการ", "Choose a business": "เลือกธุรกิจ", "Choose a new password": "ตั้งรหัสผ่านใหม่",
  "Choose a product": "เลือกผลิตภัณฑ์", "Clear": "ล้าง", "Connect channel": "เชื่อมต่อช่องทาง",
  "Connect LINE": "เชื่อมต่อ LINE", "Connect Messenger": "เชื่อมต่อ Messenger", "Connect WhatsApp": "เชื่อมต่อ WhatsApp",
  "Connector": "ตัวเชื่อมต่อ", "Connectors": "ตัวเชื่อมต่อ", "Content": "เนื้อหา", "Conversation languages": "ภาษาที่ใช้สนทนา",
  "Copy install snippet": "คัดลอกโค้ดติดตั้ง", "Create agent": "สร้างเอเจนต์", "Create bot": "สร้างบอต",
  "Create collection": "สร้างชุดความรู้", "Create contact": "สร้างข้อมูลติดต่อ", "Create lead": "สร้างข้อมูลผู้สนใจ",
  "Current availability": "สถานะพร้อมใช้งานปัจจุบัน", "Customer intents": "ความต้องการของลูกค้า",
  "Customer journeys": "เส้นทางลูกค้า", "Customer message": "ข้อความจากลูกค้า", "Customer messages": "ข้อความจากลูกค้า",
  "Customer profile": "โปรไฟล์ลูกค้า", "Customer records": "ข้อมูลลูกค้า", "Customers": "ลูกค้า", "Daily": "รายวัน",
  "Data delivery": "ส่งมอบข้อมูล", "Data erasure": "ลบข้อมูล", "Data export": "ส่งออกข้อมูล", "Day": "วัน",
  "Deploy": "ติดตั้ง", "Deployments": "การติดตั้ง", "Destination": "ปลายทาง", "Dismiss": "ปิดข้อความ",
  "Download": "ดาวน์โหลด", "Duration": "ระยะเวลา", "Edit profile": "แก้ไขโปรไฟล์", "Effective": "มีผลตั้งแต่",
  "Eligible": "มีสิทธิ์", "Email verification": "ยืนยันอีเมล", "Entry node": "โนดเริ่มต้น", "Environment": "สภาพแวดล้อม",
  "Events": "เหตุการณ์", "FlowBot studio": "สตูดิโอ FlowBot", "Handover": "ส่งต่อให้ทีม",
  "Live": "ใช้งานจริง", "Loading…": "กำลังโหลด…", "Manage": "จัดการ", "New lead": "ผู้สนใจรายใหม่",
  "Next": "ถัดไป", "No deployments": "ยังไม่มีการติดตั้ง", "Not available yet": "ยังไม่พร้อมใช้งาน",
  "Overview": "ภาพรวม", "Phone": "โทรศัพท์", "Preview": "ตัวอย่าง", "Publish": "เผยแพร่",
  "Ready": "พร้อมใช้งาน", "Save": "บันทึก", "Search": "ค้นหา", "Setup": "เริ่มใช้งาน",
  "Status": "สถานะ", "Usage": "การใช้งาน", "Voice": "ระบบเสียง", "Working…": "กำลังดำเนินการ…",
  "AI sales automation for modern merchants": "ระบบขายอัตโนมัติด้วย AI สำหรับธุรกิจยุคใหม่",
  "Convert more leads before they go cold.": "ดูแลผู้สนใจให้ทันเวลา ก่อนโอกาสขายจะหลุดมือ",
  "See features": "ดูความสามารถ", "Features": "ความสามารถ", "Start": "เริ่มต้น",
  "Main navigation": "เมนูหลัก", "Lead command center": "ศูนย์จัดการผู้สนใจ", "LINE enquiry": "ข้อความสอบถามจาก LINE",
  "Lead details": "ข้อมูลผู้สนใจ", "To your team": "ส่งต่อให้ทีม", "Thai / English": "ไทย / English",
  "Pilot — by arrangement": "โครงการนำร่อง — ติดต่อทีมงาน", "Preview — not yet for sale": "เวอร์ชันทดลอง — ยังไม่เปิดจำหน่าย",
  "Your website": "เว็บไซต์ของคุณ",
  "Answer every enquiry the moment it arrives": "ตอบทุกคำถามได้ทันทีที่ลูกค้าติดต่อ",
  "Stop hot leads from going cold overnight": "ไม่ปล่อยให้ผู้สนใจที่พร้อมซื้อหลุดมือข้ามคืน",
  "Hand the conversation to your team without losing the history": "ส่งต่อการสนทนาให้ทีมโดยข้อมูลก่อนหน้าไม่สูญหาย",
  "Capture the lead details automatically instead of retyping them": "บันทึกข้อมูลผู้สนใจอัตโนมัติ ไม่ต้องกรอกซ้ำ",
  "Review and accept the current service terms and privacy notice before registering.": "โปรดอ่านและยอมรับข้อกำหนดการให้บริการกับประกาศความเป็นส่วนตัวฉบับปัจจุบันก่อนลงทะเบียน",
  "Registration could not be completed.": "ลงทะเบียนไม่สำเร็จ กรุณาลองใหม่",
  "Check your email to continue.": "ตรวจอีเมลเพื่อดำเนินการต่อ",
  "Business outcomes": "ผลลัพธ์ทางธุรกิจ", "Three bot products": "ผลิตภัณฑ์บอต 3 รูปแบบ",
  "Where your bots can talk to customers.": "ช่องทางที่บอตใช้สนทนากับลูกค้า", "Why it works": "ทำไมจึงได้ผล",
  "Speed closes the gap between interest and purchase.": "การตอบสนองที่รวดเร็วช่วยเปลี่ยนความสนใจให้เป็นโอกาสซื้อ",
  "FlowBot, TextBot, and VoiceBot work together to convert leads faster.": "FlowBot, TextBot และ VoiceBot ทำงานร่วมกันเพื่อดูแลผู้สนใจได้เร็วขึ้น",
  "The bot answered, then handed over to the team": "บอตตอบลูกค้าแล้วส่งต่อให้ทีมงาน",
  "FlowBot asked the qualifying questions, saved the customer&apos;s details as a lead, and passed the conversation to a person when it was needed.": "FlowBot ถามคำถามเพื่อคัดกรอง บันทึกข้อมูลลูกค้าเป็นผู้สนใจ และส่งต่อการสนทนาให้ทีมงานเมื่อจำเป็น",
  "DJBOT gives your business three conversion bots in one SaaS workspace: FlowBot for guided automation, TextBot for AI messaging, and VoiceBot for website voice conversations.": "DJBOT รวมบอตช่วยการขาย 3 รูปแบบไว้ในเวิร์กสเปซ SaaS เดียว ได้แก่ FlowBot สำหรับเส้นทางอัตโนมัติ TextBot สำหรับตอบข้อความด้วย AI และ VoiceBot สำหรับสนทนาด้วยเสียงบนเว็บไซต์",
  "Most leads do not disappear because they were bad. They disappear because nobody replied fast enough, followed up clearly enough, or remembered the context when the buyer came back.": "ผู้สนใจจำนวนมากไม่ได้หายไปเพราะไม่มีโอกาสซื้อ แต่เพราะไม่ได้รับคำตอบเร็วพอ ไม่มีการติดตามที่ชัดเจน หรือทีมงานไม่เห็นบริบทเดิมเมื่อลูกค้ากลับมา",
  "Start with a product": "เลือกผลิตภัณฑ์เริ่มต้น", "Loading available products…": "กำลังโหลดผลิตภัณฑ์ที่พร้อมใช้งาน…",
  "Loading current service terms and privacy notice…": "กำลังโหลดข้อกำหนดการให้บริการและประกาศความเป็นส่วนตัวฉบับปัจจุบัน…",
  "Products could not be loaded. You can continue without selecting one.": "โหลดรายการผลิตภัณฑ์ไม่สำเร็จ คุณยังลงทะเบียนต่อได้โดยไม่ต้องเลือกผลิตภัณฑ์",
  "New product selection is temporarily closed. You can still create your owner account.": "ปิดรับการเลือกผลิตภัณฑ์ใหม่ชั่วคราว แต่คุณยังสร้างบัญชีเจ้าของได้",
  "Registration is paused because the approved service terms or privacy notice could not be loaded.": "หยุดการลงทะเบียนชั่วคราว เนื่องจากโหลดข้อกำหนดการให้บริการหรือประกาศความเป็นส่วนตัวที่อนุมัติแล้วไม่สำเร็จ",
  "Saved as your setup preference. We’ll activate this plan after payment.": "บันทึกเป็นแผนที่คุณสนใจแล้ว ระบบจะเปิดใช้งานหลังได้รับการชำระเงิน",
  "I accept the": "ยอมรับ", "Service Terms": "ข้อกำหนดการให้บริการ", "Privacy Notice": "ประกาศความเป็นส่วนตัว",
  "Use 12–128 characters. A long, unique passphrase is recommended.": "ใช้ 12–128 ตัวอักษร และควรเป็นรหัสผ่านที่ยาว ไม่ซ้ำกับบริการอื่น",
  "Open the verification link to create the workspace and owner access. You can safely request another link below if the first email does not arrive.": "เปิดลิงก์ยืนยันในอีเมลเพื่อสร้างเวิร์กสเปซและสิทธิ์เจ้าของ หากไม่ได้รับอีเมลฉบับแรก คุณสามารถขอลิงก์ใหม่ด้านล่างได้",
  "Account links": "ลิงก์บัญชี", "Account sign in": "เข้าสู่บัญชี", "Approved customer document": "เอกสารสำหรับลูกค้าที่อนุมัติแล้ว",
  "Checking service": "กำลังตรวจสอบบริการ", "Clear, provider-neutral updates": "ข้อมูลสถานะที่ชัดเจนโดยไม่เปิดเผยผู้ให้บริการเบื้องหลัง",
  "Confirm your owner account": "ยืนยันบัญชีเจ้าของ", "Create or view an account": "สร้างหรือเปิดบัญชี",
  "Current evidence could not be loaded.": "โหลดหลักฐานสถานะปัจจุบันไม่สำเร็จ", "Customer-facing systems": "ระบบที่ลูกค้าใช้งาน",
  "DJAY Bot home": "หน้าแรก DJAY Bot", "DJAY Bot service status": "สถานะบริการ DJAY Bot", "Join your workspace": "เข้าร่วมเวิร์กสเปซ",
  "Loading the current approved document…": "กำลังโหลดเอกสารฉบับปัจจุบันที่อนุมัติแล้ว…", "Need a new verification link?": "ต้องการลิงก์ยืนยันใหม่?",
  "No operational claim is being made.": "ยังไม่มีข้อมูลเพียงพอสำหรับยืนยันสถานะการทำงาน", "Page unavailable": "หน้าไม่พร้อมใช้งาน",
  "Public navigation": "เมนูสาธารณะ", "Registration remains paused until the approved version can be reviewed.": "การลงทะเบียนจะหยุดชั่วคราวจนกว่าจะเปิดอ่านเอกสารฉบับที่อนุมัติได้",
  "Return home": "กลับหน้าแรก", "Review the current approved document before creating a workspace.": "โปรดอ่านเอกสารฉบับปัจจุบันที่อนุมัติก่อนสร้างเวิร์กสเปซ",
  "Secure link loading...": "กำลังโหลดลิงก์ที่ปลอดภัย...", "Set your account details to accept this invitation.": "กรอกข้อมูลบัญชีเพื่อยอมรับคำเชิญนี้",
  "Sign in first": "โปรดเข้าสู่ระบบก่อน", "Team invitation": "คำเชิญเข้าร่วมทีม",
  "The address may have changed or the link may be incomplete. Your account and workspace data have not been changed.": "ที่อยู่นี้อาจเปลี่ยนไปหรือลิงก์ไม่ครบถ้วน ข้อมูลบัญชีและเวิร์กสเปซของคุณยังไม่ถูกเปลี่ยนแปลง",
  "This document is temporarily unavailable.": "เอกสารนี้ไม่พร้อมใช้งานชั่วคราว", "This page is not here.": "ไม่พบหน้าที่ต้องการ",
  "This page reports the DJAY Bot services customers use. It does not expose infrastructure vendors, internal routing, customer data, or security-sensitive incident details.": "หน้านี้รายงานสถานะบริการ DJAY Bot ที่ลูกค้าใช้งาน โดยไม่เปิดเผยผู้ให้บริการโครงสร้างพื้นฐาน เส้นทางภายใน ข้อมูลลูกค้า หรือรายละเอียดเหตุการณ์ที่อ่อนไหวต่อความปลอดภัย",
  "Try the page again. If it still does not load, return to the website or check current service status.": "ลองโหลดหน้านี้อีกครั้ง หากยังไม่สำเร็จให้กลับเว็บไซต์หรือตรวจสอบสถานะบริการปัจจุบัน",
  "We could not finish loading this page.": "โหลดหน้านี้ไม่สำเร็จ", "Your workspace is ready. Sign in with the password you created.": "เวิร์กสเปซพร้อมแล้ว เข้าสู่ระบบด้วยรหัสผ่านที่คุณสร้าง",
  "AI Chat analytics could not be loaded": "โหลดข้อมูลวิเคราะห์แชต AI ไม่สำเร็จ", "Accept with your existing account": "ยอมรับด้วยบัญชีที่มีอยู่",
  "Access expires": "สิทธิ์หมดอายุ", "Access token": "Access token", "Account activity": "กิจกรรมในบัญชี",
  "Account credit": "เครดิตในบัญชี", "Account overview": "ภาพรวมบัญชี", "Active calls": "สายที่กำลังใช้งาน",
  "Active holds appear here before erasure.": "รายการที่ระงับการลบจะแสดงที่นี่ก่อนดำเนินการลบข้อมูล", "Active members": "สมาชิกที่ใช้งานอยู่",
  "Active records": "รายการที่ใช้งานอยู่", "Active team": "ทีมที่ใช้งานอยู่", "Active team members could not be loaded.": "โหลดสมาชิกทีมที่ใช้งานอยู่ไม่สำเร็จ",
  "Add a merchant inbox to receive durable lead notifications.": "เพิ่มอีเมลธุรกิจเพื่อรับการแจ้งเตือนผู้สนใจที่ส่งซ้ำได้อย่างปลอดภัย",
  "Add a source in Knowledge & Sales Setup.": "เพิ่มแหล่งข้อมูลในหน้าคลังความรู้และการตั้งค่าการขาย", "Add attribute": "เพิ่มแอตทริบิวต์",
  "Add or reactivate a team member before creating a routing team.": "เพิ่มหรือเปิดใช้งานสมาชิกทีมก่อนสร้างทีมรับช่วงการสนทนา",
  "Add this snippet only to the approved website origin.": "ติดตั้งโค้ดนี้เฉพาะบนต้นทางเว็บไซต์ที่อนุมัติแล้ว", "Add-on": "ส่วนเสริม",
  "Addresses are encrypted. Only the fixed qualified-lead template is allowed.": "ที่อยู่อีเมลถูกเข้ารหัส และส่งได้เฉพาะเทมเพลตผู้สนใจที่ผ่านการคัดกรองแล้ว",
  "Advanced AI sales playbook JSON": "คู่มือการขาย AI แบบ JSON ขั้นสูง", "Advanced JSON": "JSON ขั้นสูง",
  "Agent and deployment records remain available.": "ข้อมูลเอเจนต์และการติดตั้งจะยังคงอยู่", "Allowance not commercially configured": "ยังไม่ได้กำหนดโควตาเชิงพาณิชย์",
  "Allowance thresholds": "เกณฑ์โควตา", "Allowed website origins": "ต้นทางเว็บไซต์ที่อนุญาต", "App secret": "App secret",
  "Approved connectors become available to webhook nodes.": "ตัวเชื่อมต่อที่อนุมัติแล้วจะเลือกใช้ได้ในโนด webhook",
  "Approved conversation guidance": "แนวทางการสนทนาที่อนุมัติ", "Assistant identity and goals": "ตัวตนและเป้าหมายของผู้ช่วย",
  "Audio contract": "ข้อกำหนดระบบเสียง", "Authentication": "การยืนยันตัวตน",
  "Automated-agent disclosure is required before ordinary assistant speech.": "ต้องแจ้งว่ากำลังสนทนากับระบบอัตโนมัติก่อนเริ่มข้อความทั่วไปของผู้ช่วย",
  "Average connected time": "เวลาเชื่อมต่อเฉลี่ย", "Average turn response": "เวลาตอบแต่ละช่วงเฉลี่ย", "Basic channel": "ช่องทางพื้นฐาน",
  "Basic downgrade preflight": "ตรวจความพร้อมก่อนลดเป็นแผน Basic", "Billing documents are temporarily unavailable.": "เอกสารการเรียกเก็บเงินไม่พร้อมใช้งานชั่วคราว",
  "Billing managers and owners": "ผู้จัดการการเรียกเก็บเงินและเจ้าของ", "Billing notifications": "การแจ้งเตือนการเรียกเก็บเงิน",
  "Billing recipient": "ผู้รับเอกสารการเรียกเก็บเงิน", "Bot and deployment records remain available.": "ข้อมูลบอตและการติดตั้งจะยังคงอยู่",
  "Browser admission boundary": "ขอบเขตการอนุญาตจากเบราว์เซอร์", "Browser origin": "ต้นทางเบราว์เซอร์",
  "Business account ID": "รหัสบัญชีธุรกิจ", "Business account reference": "รหัสอ้างอิงบัญชีธุรกิจ", "Business content": "เนื้อหาธุรกิจ",
  "Business requirement": "ความต้องการทางธุรกิจ", "CTA policy": "แนวทางคำกระตุ้นให้ดำเนินการ", "Call / Session Entry": "การเริ่มสาย / เซสชัน",
  "Callback intent is captured as an authorized follow-up with customer-provided contact details and time preference. The agent never promises an unconfirmed appointment.": "ระบบบันทึกความต้องการให้ติดต่อกลับเป็นงานติดตามที่ได้รับอนุญาต พร้อมช่องทางติดต่อและเวลาที่ลูกค้าแจ้ง เอเจนต์จะไม่รับปากนัดหมายที่ยังไม่ได้ยืนยัน",
  "Calls reconnected": "สายที่เชื่อมต่อใหม่", "Calls to action": "คำกระตุ้นให้ดำเนินการ", "Capacity and presentation": "ความจุและรูปแบบการแสดงผล",
  "Channel access token": "Channel access token", "Channel and notification tools require authoring access": "เครื่องมือช่องทางและการแจ้งเตือนต้องมีสิทธิ์แก้ไข",
  "Channel secret": "Channel secret", "Choose a product above to save your setup preference, then continue to payment when checkout is available. Pilot activation remains for named comps only.": "เลือกผลิตภัณฑ์ด้านบนเพื่อบันทึกความสนใจ แล้วดำเนินการชำระเงินเมื่อระบบเปิดให้บริการ การเปิดใช้แบบนำร่องสงวนไว้สำหรับบัญชีที่ได้รับอนุมัติเท่านั้น",
  "Closes": "ปิดเวลา", "Collections": "ชุดความรู้", "Completed / failed": "เสร็จสิ้น / ล้มเหลว", "Completed turns": "ช่วงสนทนาที่เสร็จสิ้น",
  "Completion rate": "อัตราสำเร็จ", "Confidence escalation threshold": "เกณฑ์ความมั่นใจสำหรับส่งต่อ", "Confirm new password": "ยืนยันรหัสผ่านใหม่",
  "Confirm ownership transfer": "ยืนยันการโอนสิทธิ์เจ้าของ", "Confirm the snippet is on the exact allowed origin.": "ยืนยันว่าโค้ดอยู่บนต้นทางเว็บไซต์ที่อนุญาตตรงกันทุกตัวอักษร",
  "Connect LINE OA or Messenger to the selected published bot.": "เชื่อมต่อ LINE OA หรือ Messenger กับบอตที่เผยแพร่และเลือกไว้",
  "Connect a LINE Official Account": "เชื่อมต่อบัญชีทางการ LINE", "Connect a Messenger Page": "เชื่อมต่อเพจ Messenger",
  "Connect a WhatsApp Business number": "เชื่อมต่อหมายเลข WhatsApp Business", "Consent": "ความยินยอม",
  "Continue in Setup wizard": "ดำเนินการต่อในตัวช่วยตั้งค่า", "Continue to payment": "ดำเนินการชำระเงิน",
  "Contract boundaries": "ขอบเขตสัญญาการทำงาน", "Controls": "การควบคุม", "Conversations retained under hold": "การสนทนาที่เก็บไว้ตามคำสั่งระงับการลบ",
  "Cooldown": "ช่วงพัก", "Crawl a website page": "สแกนหน้าเว็บไซต์", "Create and publish a bot before deploying.": "สร้างและเผยแพร่บอตก่อนติดตั้ง",
  "Create another Voice Agent deployment": "สร้างการติดตั้ง Voice Agent เพิ่ม", "Create one from a contact.": "สร้างจากข้อมูลติดต่อ",
  "Create or select a bot above, then publish from the Flow tab. First-time merchants should prefer the guided wizard.": "สร้างหรือเลือกบอตด้านบน แล้วเผยแพร่จากแท็บ Flow หากใช้งานครั้งแรก แนะนำให้ใช้ตัวช่วยตั้งค่าทีละขั้น",
  "Create the first grounded sales assistant.": "สร้างผู้ช่วยฝ่ายขายที่อ้างอิงข้อมูลจริงรายการแรก", "Create the knowledge boundary for your first agent.": "กำหนดขอบเขตคลังความรู้สำหรับเอเจนต์รายการแรก",
  "Credentials and the verify token are encrypted and never shown again. Replies are allowed only inside the customer-service window.": "ข้อมูลรับรองและ verify token จะถูกเข้ารหัสและไม่แสดงอีกครั้ง การตอบกลับทำได้เฉพาะภายในช่วงเวลาบริการลูกค้า",
  "Credentials are encrypted and never shown again. Use a stable internal account reference, not a secret.": "ข้อมูลรับรองจะถูกเข้ารหัสและไม่แสดงอีกครั้ง ให้ใช้รหัสอ้างอิงบัญชีภายในที่คงที่ ไม่ใช่ข้อมูลลับ",
  "Currency": "สกุลเงิน", "Current definitions are compatible with FlowBot Basic.": "การตั้งค่าปัจจุบันรองรับ FlowBot Basic",
  "Current entitlement authority": "สิทธิ์ผลิตภัณฑ์ปัจจุบัน", "Customer records appear here.": "ข้อมูลลูกค้าจะแสดงที่นี่",
  "DJAY Bot workspace": "เวิร์กสเปซ DJAY Bot", "Delivery": "การส่งข้อมูล", "Denied": "ไม่อนุญาต", "Deployment name": "ชื่อการติดตั้ง",
  "Deterministic": "ทำงานตามกติกา", "Deterministic messaging": "ข้อความตามกติกาที่กำหนด", "Directory": "รายชื่อ",
  "Disclosure & Recording": "การแจ้งผู้ใช้และการบันทึก", "Disclosure first · recording off · bounded reconnect": "แจ้งผู้ใช้ก่อน · ปิดการบันทึก · จำกัดการเชื่อมต่อใหม่",
  "Discovery questions": "คำถามค้นหาความต้องการ", "Document": "เอกสาร", "Downgrade compatibility could not be checked": "ตรวจความเข้ากันได้ก่อนลดแผนไม่สำเร็จ",
  "Download recovery codes": "ดาวน์โหลดรหัสกู้คืน", "Draft revision": "ฉบับร่างเวอร์ชัน", "Email action profiles could not be loaded.": "โหลดโปรไฟล์การส่งอีเมลไม่สำเร็จ",
  "Email billing events": "เหตุการณ์เรียกเก็บเงินทางอีเมล", "English + Thai": "English + ไทย",
  "Enter at least one customer contact method: email or phone.": "กรอกช่องทางติดต่อลูกค้าอย่างน้อยหนึ่งรายการ: อีเมลหรือโทรศัพท์",
  "Enter one item per line. The assistant can use approved claims and must avoid prohibited claims.": "กรอกหนึ่งรายการต่อบรรทัด ผู้ช่วยใช้ได้เฉพาะข้อความที่อนุมัติและต้องหลีกเลี่ยงข้อความต้องห้าม",
  "Escalation and customer actions": "การส่งต่อและการดำเนินการสำหรับลูกค้า", "Event keys": "คีย์เหตุการณ์",
  "Evidence-based on Overview": "อ้างอิงหลักฐานในหน้าภาพรวม", "Exact HTTPS origins, one per line": "ต้นทาง HTTPS ที่ตรงกันทุกตัวอักษร บรรทัดละหนึ่งรายการ",
  "Exact allowed website origin": "ต้นทางเว็บไซต์ที่อนุญาตแบบตรงกันทุกตัวอักษร", "Executions": "การทำงาน",
  "Existing LINE settings have not changed.": "การตั้งค่า LINE เดิมไม่ถูกเปลี่ยน", "Existing Messenger settings have not changed.": "การตั้งค่า Messenger เดิมไม่ถูกเปลี่ยน",
  "Existing WhatsApp settings have not changed.": "การตั้งค่า WhatsApp เดิมไม่ถูกเปลี่ยน", "Existing delivery settings have not changed.": "การตั้งค่าการส่งข้อมูลเดิมไม่ถูกเปลี่ยน",
  "Expires": "หมดอายุ", "Export or erase personal data": "ส่งออกหรือลบข้อมูลส่วนบุคคล", "External API": "API ภายนอก",
  "Facebook Messenger": "Facebook Messenger", "Failed / expired": "ล้มเหลว / หมดอายุ", "First year": "ปีแรก",
  "Flow Bot": "FlowBot", "Flow bots": "FlowBot", "Flow templates": "เทมเพลต Flow", "FlowBot analytics": "ข้อมูลวิเคราะห์ FlowBot",
  "FlowBot analytics could not be loaded": "โหลดข้อมูลวิเคราะห์ FlowBot ไม่สำเร็จ", "FlowBot studio areas": "ส่วนต่าง ๆ ในสตูดิโอ FlowBot",
  "For example: Asia/Bangkok": "ตัวอย่าง: Asia/Bangkok", "Forecast confidence": "ความมั่นใจของการคาดการณ์", "Forecast exhaustion": "คาดว่าจะใช้หมดเมื่อ",
  "Forgot password?": "ลืมรหัสผ่าน?", "Google Sheets": "Google Sheets", "Governance": "การกำกับดูแล", "Graceful escalation": "การส่งต่ออย่างเหมาะสม",
  "Granted": "อนุญาตแล้ว", "Greeting": "คำทักทาย", "Grounded business facts": "ข้อเท็จจริงทางธุรกิจที่ตรวจสอบได้",
  "Grounded sales conversations": "การสนทนาการขายที่อ้างอิงข้อมูลจริง", "Grounded turns": "ช่วงสนทนาที่อ้างอิงข้อมูลจริง",
  "Guided setup": "ตัวช่วยตั้งค่าทีละขั้น", "HTTPS endpoint": "ปลายทาง HTTPS", "HTTPS page URL": "URL หน้าเว็บแบบ HTTPS",
  "Human handover": "ส่งต่อให้ทีมงาน", "Human handover changes the shared conversation to human mode.": "เมื่อส่งต่อให้ทีม การสนทนาร่วมจะเปลี่ยนเป็นโหมดเจ้าหน้าที่",
  "IANA timezone": "เขตเวลามาตรฐาน IANA", "Identity and conversation opening": "ตัวตนและการเริ่มสนทนา", "Immutable history": "ประวัติที่แก้ไขไม่ได้",
  "Immutable on publish": "แก้ไขไม่ได้หลังเผยแพร่", "Immutable release and browser install": "เวอร์ชันถาวรและการติดตั้งบนเบราว์เซอร์",
  "Included allowance": "โควตาที่รวมในแผน", "Invitation": "คำเชิญ", "Invitations": "คำเชิญ", "Invite a team member": "เชิญสมาชิกทีม",
  "Invoices and plan management": "ใบแจ้งหนี้และการจัดการแผน", "Keep transcripts for": "เก็บข้อความการสนทนาเป็นเวลา",
  "Knowledge boundaries": "ขอบเขตคลังความรู้", "Knowledge options could not be loaded": "โหลดตัวเลือกคลังความรู้ไม่สำเร็จ",
  "Knowledge options could not be loaded.": "โหลดตัวเลือกคลังความรู้ไม่สำเร็จ", "Label": "ป้ายกำกับ", "Language mix": "สัดส่วนภาษา",
  "Last": "ล่าสุด", "Last active": "ใช้งานล่าสุด", "Last session:": "เซสชันล่าสุด:", "Launch checklist": "รายการตรวจสอบก่อนเปิดใช้",
  "Lead & sales facts": "ข้อมูลผู้สนใจและการขาย", "Lead capture": "การเก็บข้อมูลผู้สนใจ", "Lead delivery": "การส่งข้อมูลผู้สนใจ",
  "Lead segments": "กลุ่มผู้สนใจ", "Leads / appointments": "ผู้สนใจ / นัดหมาย", "Leads captured": "ผู้สนใจที่เก็บข้อมูลได้",
  "Leave empty until verified": "เว้นว่างไว้จนกว่าจะตรวจสอบแล้ว", "Legal hold": "ระงับการลบตามข้อกำหนด", "Loading AI Chat…": "กำลังโหลดแชต AI…",
  "Loading FlowBot...": "กำลังโหลด FlowBot...", "Loading Voice Studio...": "กำลังโหลดสตูดิโอเสียง...", "Loading contacts...": "กำลังโหลดข้อมูลติดต่อ...",
  "Loading current usage…": "กำลังโหลดการใช้งานปัจจุบัน…", "Loading data controls...": "กำลังโหลดการจัดการข้อมูล...", "Loading inbox...": "กำลังโหลดกล่องข้อความ...",
  "Loading knowledge...": "กำลังโหลดคลังความรู้...", "Loading leads...": "กำลังโหลดผู้สนใจ...", "Loading products…": "กำลังโหลดผลิตภัณฑ์…",
  "Loading retention policy...": "กำลังโหลดนโยบายการเก็บรักษาข้อมูล...", "Loading security...": "กำลังโหลดข้อมูลความปลอดภัย...",
  "Loading services...": "กำลังโหลดบริการ...", "Loading settings…": "กำลังโหลดการตั้งค่า…", "Loading setup…": "กำลังโหลดการตั้งค่าเริ่มต้น…",
  "Loading team...": "กำลังโหลดทีมงาน...", "Loading usage...": "กำลังโหลดการใช้งาน...", "Loading workspace...": "กำลังโหลดเวิร์กสเปซ...",
  "Low-confidence questions": "คำถามที่มีความมั่นใจต่ำ", "Lower-confidence answers are transferred to your team.": "คำถามที่ระบบตอบได้ด้วยความมั่นใจต่ำจะส่งต่อให้ทีมงาน",
  "Mandatory opening policy": "ข้อกำหนดการเปิดบทสนทนา", "Mark read": "ทำเครื่องหมายว่าอ่านแล้ว", "Members": "สมาชิก",
  "Merchant email": "อีเมลธุรกิจ", "Merchant email notifications": "การแจ้งเตือนทางอีเมลธุรกิจ", "Merchant-authorized test mode": "โหมดทดสอบที่ธุรกิจอนุญาต",
  "Messages": "ข้อความ", "Messages are ordered and tenant scoped.": "ข้อความเรียงตามลำดับและแยกตามเวิร์กสเปซ", "Messages could not be loaded.": "โหลดข้อความไม่สำเร็จ",
  "Messenger connections": "การเชื่อมต่อ Messenger", "Microphone permission · PCM16 · interruption enabled": "สิทธิ์ไมโครโฟน · PCM16 · รองรับการพูดแทรก",
  "Minutes used": "นาทีที่ใช้", "Monthly": "รายเดือน", "Multi-factor authentication": "การยืนยันตัวตนหลายขั้นตอน",
  "Name, language, and timezone": "ชื่อ ภาษา และเขตเวลา", "Needs review": "ต้องตรวจสอบ", "New access token": "Access token ใหม่",
  "New app secret": "App secret ใหม่", "New channel secret": "Channel secret ใหม่", "New page access token": "Page access token ใหม่",
  "New password": "รหัสผ่านใหม่", "New record": "รายการใหม่", "New shared email or phone values appear here for review.": "อีเมลหรือโทรศัพท์ที่ซ้ำกับรายการอื่นจะแสดงที่นี่เพื่อตรวจสอบ",
  "New verify token": "Verify token ใหม่", "Next action:": "ขั้นตอนถัดไป:", "No AI agents": "ยังไม่มีเอเจนต์ AI", "No FlowBots": "ยังไม่มี FlowBot",
  "No LINE connection": "ยังไม่ได้เชื่อมต่อ LINE", "No Messenger connection": "ยังไม่ได้เชื่อมต่อ Messenger", "No Voice deployment": "ยังไม่มีการติดตั้งระบบเสียง",
  "No WhatsApp connection": "ยังไม่ได้เชื่อมต่อ WhatsApp", "No active product yet": "ยังไม่มีผลิตภัณฑ์ที่เปิดใช้งาน", "No active team members": "ไม่มีสมาชิกทีมที่ใช้งานอยู่",
  "No approved knowledge": "ยังไม่มีความรู้ที่อนุมัติ", "No billing activity yet": "ยังไม่มีกิจกรรมการเรียกเก็บเงิน", "No billing documents yet": "ยังไม่มีเอกสารการเรียกเก็บเงิน",
  "No business-hour windows. The offline message will be used.": "ยังไม่ได้กำหนดเวลาทำการ ระบบจะใช้ข้อความนอกเวลาทำการ", "No classified intents in this period.": "รอบนี้ยังไม่มีการจำแนกความต้องการ",
  "No classified outcomes yet.": "ยังไม่มีการจำแนกผลลัพธ์", "No collection": "ยังไม่มีชุดความรู้", "No connectors": "ยังไม่มีตัวเชื่อมต่อ",
  "No contacts": "ยังไม่มีข้อมูลติดต่อ", "No email action": "ยังไม่มีการส่งอีเมล", "No failed turns.": "ไม่มีช่วงสนทนาที่ล้มเหลว",
  "No journey data": "ยังไม่มีข้อมูลเส้นทางลูกค้า", "No keyword misses in this period.": "รอบนี้ไม่มีคีย์เวิร์ดที่ตอบไม่ได้", "No leads": "ยังไม่มีผู้สนใจ",
  "No legal holds": "ไม่มีคำสั่งระงับการลบ", "No possible matches": "ไม่พบรายการที่อาจซ้ำกัน", "No privacy requests": "ยังไม่มีคำขอด้านความเป็นส่วนตัว",
  "No products are available to select right now.": "ขณะนี้ไม่มีผลิตภัณฑ์ที่เลือกได้", "No questions in this period.": "รอบนี้ยังไม่มีคำถาม",
  "No ready source": "ยังไม่มีแหล่งข้อมูลที่พร้อมใช้", "No recipients": "ยังไม่มีผู้รับ", "No scored customers yet.": "ยังไม่มีลูกค้าที่ประเมินคะแนนแล้ว",
  "No sessions yet.": "ยังไม่มีเซสชัน", "No social channels": "ยังไม่มีช่องทางโซเชียล", "No subscription change has been made.": "ยังไม่มีการเปลี่ยนแปลงการสมัครใช้บริการ",
  "No terminal calls yet.": "ยังไม่มีสายที่สิ้นสุด", "No unanswered inputs": "ไม่มีข้อความที่ยังไม่ได้ตอบ", "No usage currently reserved": "ไม่มีโควตาที่ถูกจองใช้อยู่",
  "Node settings": "การตั้งค่าโนด", "Notification recipients could not be loaded": "โหลดรายชื่อผู้รับการแจ้งเตือนไม่สำเร็จ", "Number": "หมายเลข",
  "One approved instruction per line": "คำสั่งที่อนุมัติแล้วบรรทัดละหนึ่งรายการ", "One field per line": "หนึ่งช่องข้อมูลต่อบรรทัด",
  "One guardrail per line": "ข้อจำกัดบรรทัดละหนึ่งรายการ", "One per line": "หนึ่งรายการต่อบรรทัด", "One-time LINE webhook URL": "Webhook URL ของ LINE ที่แสดงครั้งเดียว",
  "One-time Messenger callback URL": "Callback URL ของ Messenger ที่แสดงครั้งเดียว", "One-time Voice deployment key and install snippet": "กุญแจติดตั้งระบบเสียงและโค้ดติดตั้งที่แสดงครั้งเดียว",
  "One-time WhatsApp callback URL": "Callback URL ของ WhatsApp ที่แสดงครั้งเดียว", "One-time deployment key": "กุญแจติดตั้งที่แสดงครั้งเดียว",
  "Only selected ready revisions are copied into the next immutable playbook. Existing calls remain pinned to their original knowledge.": "ระบบจะคัดลอกเฉพาะฉบับที่พร้อมและเลือกไว้ไปยังคู่มือเวอร์ชันถาวรถัดไป สายเดิมยังคงใช้คลังความรู้เวอร์ชันเดิม",
  "Open Flow editor": "เปิดตัวแก้ไข Flow", "Open Knowledge & Sales Setup": "เปิดคลังความรู้และการตั้งค่าการขาย", "Open guided Setup wizard": "เปิดตัวช่วยตั้งค่าทีละขั้น",
  "Open setup": "เปิดการตั้งค่า", "Open that site, start the widget, and finish one greeting or lead journey on the current published version.": "เปิดเว็บไซต์นั้น เริ่มวิดเจ็ต และสนทนาให้จบหนึ่งเส้นทางด้วยเวอร์ชันที่เผยแพร่ปัจจุบัน",
  "Open the read-only conversation map": "เปิดผังการสนทนาแบบดูอย่างเดียว", "Opens": "เปิดเวลา", "Opportunity": "โอกาสขาย", "Outcome": "ผลลัพธ์",
  "Overage": "การใช้เกินโควตา", "Ownership": "สิทธิ์เจ้าของ", "Page ID": "Page ID", "Page access token": "Page access token",
  "Page account reference": "รหัสอ้างอิงบัญชีเพจ", "Password updated. All previous sessions were signed out.": "อัปเดตรหัสผ่านแล้ว และออกจากระบบทุกเซสชันก่อนหน้า",
  "Paste this into LINE Developers, enable webhooks, then run a health check below.": "นำค่านี้ไปวางใน LINE Developers เปิดใช้ webhook แล้วตรวจสถานะด้านล่าง",
  "Path performance": "ประสิทธิภาพของเส้นทาง", "Payment activates access for this product.": "การชำระเงินจะเปิดสิทธิ์ใช้ผลิตภัณฑ์นี้", "Pending": "รอดำเนินการ",
  "Phone number ID": "Phone number ID", "Plan access": "สิทธิ์ตามแผน", "Plan safety": "ความปลอดภัยในการเปลี่ยนแผน", "Plans and usage": "แผนและการใช้งาน",
  "Platform support access is active": "สิทธิ์ช่วยเหลือจากทีมแพลตฟอร์มกำลังใช้งาน", "Possible contact matches": "ข้อมูลติดต่อที่อาจเป็นรายการเดียวกัน",
  "Premium feature": "ความสามารถพรีเมียม", "Premium operations": "การดำเนินงานพรีเมียม", "Premium social channels": "ช่องทางโซเชียลพรีเมียม",
  "Preview without side effects": "ดูตัวอย่างโดยไม่เปลี่ยนข้อมูล", "Price": "ราคา", "Prices come from the server catalog": "ราคาอ้างอิงจากรายการผลิตภัณฑ์บนเซิร์ฟเวอร์",
  "Privacy exports and erasure requests are reserved for the registered workspace owner.": "การส่งออกและคำขอลบข้อมูลส่วนบุคคลจำกัดไว้สำหรับเจ้าของเวิร์กสเปซที่ลงทะเบียน",
  "Privacy requests": "คำขอด้านความเป็นส่วนตัว", "Processing": "กำลังดำเนินการ", "Product contract": "ข้อกำหนดผลิตภัณฑ์",
  "Product onboarding": "การเริ่มใช้ผลิตภัณฑ์", "Product setup progress": "ความคืบหน้าการตั้งค่าผลิตภัณฑ์", "Products and services": "ผลิตภัณฑ์และบริการ",
  "Products could not be loaded": "โหลดผลิตภัณฑ์ไม่สำเร็จ", "Professional delivery": "บริการดำเนินงานโดยผู้เชี่ยวชาญ", "Prohibited claims": "ข้อความต้องห้าม",
  "Projected overage": "คาดการณ์การใช้เกินโควตา", "Projected use": "การใช้งานที่คาดการณ์", "Provider webhook URL": "Webhook URL ของผู้ให้บริการ",
  "Provisioned after approval": "จัดเตรียมหลังได้รับอนุมัติ", "Public agent name": "ชื่อเอเจนต์ที่แสดงต่อสาธารณะ",
  "Publish before creating a web deployment.": "เผยแพร่ก่อนสร้างการติดตั้งบนเว็บ", "Publish before creating a website deployment.": "เผยแพร่ก่อนสร้างการติดตั้งบนเว็บไซต์",
  "Publish copy": "เผยแพร่ข้อความ", "Publish the agent, then connect its LINE Official Account.": "เผยแพร่เอเจนต์แล้วเชื่อมต่อบัญชีทางการ LINE",
  "Publish the agent, then connect its Messenger Page.": "เผยแพร่เอเจนต์แล้วเชื่อมต่อเพจ Messenger", "Publish the agent, then connect its WhatsApp Business number.": "เผยแพร่เอเจนต์แล้วเชื่อมต่อหมายเลข WhatsApp Business",
  "Published assistants": "ผู้ช่วยที่เผยแพร่แล้ว", "Published flow paths appear after customer executions.": "เส้นทาง Flow ที่เผยแพร่จะแสดงหลังมีลูกค้าใช้งาน",
  "Published playbook": "คู่มือที่เผยแพร่แล้ว", "Published sales behavior": "แนวทางการขายที่เผยแพร่แล้ว", "Published versions": "เวอร์ชันที่เผยแพร่แล้ว",
  "Qualified lead delivery": "การส่งข้อมูลผู้สนใจที่ผ่านการคัดกรอง", "Qualified lead, VIP, Follow up": "ผู้สนใจที่ผ่านการคัดกรอง, VIP, ติดตาม",
  "Qualified-lead email profile": "โปรไฟล์อีเมลแจ้งผู้สนใจที่ผ่านการคัดกรอง", "Qualified-lead recipient": "ผู้รับข้อมูลผู้สนใจที่ผ่านการคัดกรอง",
  "Quality Evaluation": "การประเมินคุณภาพ", "Quantity": "จำนวน", "Queue crawl": "เพิ่มงานสแกนเข้าคิว", "Queued crawls and uploads appear after scanning and extraction.": "งานสแกนและไฟล์อัปโหลดในคิวจะแสดงหลังประมวลผลและดึงข้อมูล",
  "Ready revisions": "ฉบับที่พร้อมใช้", "Recent billing notifications": "การแจ้งเตือนการเรียกเก็บเงินล่าสุด", "Recent call trend": "แนวโน้มสายล่าสุด",
  "Recipient addresses are encrypted. Only the approved lead-captured template can be sent.": "ที่อยู่ผู้รับถูกเข้ารหัส และส่งได้เฉพาะเทมเพลตแจ้งผู้สนใจที่อนุมัติแล้ว",
  "Recipient email": "อีเมลผู้รับ", "Recipient name": "ชื่อผู้รับ", "Recipient options could not be loaded.": "โหลดตัวเลือกผู้รับไม่สำเร็จ",
  "Reconnect window seconds": "ช่วงเวลาเชื่อมต่อใหม่ (วินาที)", "Recording off": "ปิดการบันทึก", "Recovery codes": "รหัสกู้คืน",
  "Reference": "ข้อมูลอ้างอิง", "Refresh": "รีเฟรช", "Refresh before handling customer data or making workspace changes.": "รีเฟรชก่อนจัดการข้อมูลลูกค้าหรือเปลี่ยนแปลงเวิร์กสเปซ",
  "Release automation": "ระบบเผยแพร่อัตโนมัติ", "Remove access": "นำสิทธิ์ออก", "Remove attribute": "นำแอตทริบิวต์ออก", "Renewal": "การต่ออายุ",
  "Replies cannot be blank and may contain up to 20,000 characters.": "ข้อความตอบกลับต้องไม่ว่างและยาวได้สูงสุด 20,000 ตัวอักษร", "Reply": "ตอบกลับ",
  "Request an add-on": "ขอส่วนเสริม", "Request an additional administrator": "ขอผู้ดูแลเพิ่มเติม", "Request consultation": "ขอนัดปรึกษา",
  "Request history": "ประวัติคำขอ", "Required contact details": "ข้อมูลติดต่อที่จำเป็น", "Required contact fields": "ช่องข้อมูลติดต่อที่จำเป็น",
  "Reset your password": "รีเซ็ตรหัสผ่าน", "Resources and seats": "ทรัพยากรและจำนวนผู้ใช้", "Retry messages": "ลองส่งข้อความใหม่",
  "Return to overview": "กลับหน้าภาพรวม", "Return to sign in": "กลับหน้าเข้าสู่ระบบ", "Return to workspace": "กลับเวิร์กสเปซ",
  "Revoke permanently": "เพิกถอนถาวร", "Role": "บทบาท", "Role for": "บทบาทของ", "Rotate": "เปลี่ยนกุญแจ", "Rotate credentials": "เปลี่ยนข้อมูลรับรอง",
  "Routing team": "ทีมรับช่วงการสนทนา", "Routing team key": "คีย์ทีมรับช่วง", "Run safe preview": "เรียกดูตัวอย่างอย่างปลอดภัย",
  "Runtime policy": "นโยบายขณะทำงาน", "Safe deployment key prefix": "คำนำหน้ากุญแจติดตั้งที่เปิดเผยได้", "Safe preflight": "ตรวจสอบล่วงหน้าอย่างปลอดภัย",
  "Sales": "การขาย", "Sales Playbook": "คู่มือการขาย", "Sales assistants": "ผู้ช่วยฝ่ายขาย", "Sales inbox": "กล่องข้อความฝ่ายขาย", "Sales outcomes": "ผลลัพธ์การขาย",
  "Save 09:00-17:00 weekdays": "บันทึกวันธรรมดา 09:00–17:00", "Save alerts": "บันทึกการแจ้งเตือน", "Save item": "บันทึกรายการ",
  "Save notifications": "บันทึกการแจ้งเตือน", "Save plan preference": "บันทึกแผนที่สนใจ", "Save routing team": "บันทึกทีมรับช่วง",
  "Save the current draft before publishing.": "บันทึกฉบับร่างปัจจุบันก่อนเผยแพร่", "Scan with your authenticator app, or enter the setup key manually.": "สแกนด้วยแอปยืนยันตัวตนหรือกรอก setup key ด้วยตนเอง",
  "Scanned documents": "เอกสารที่สแกนแล้ว", "Scheduled import": "นำเข้าตามกำหนดเวลา", "Schedules and routing": "ตารางเวลาและการส่งต่อ",
  "Search contacts": "ค้นหาข้อมูลติดต่อ", "Search name, phone, or email": "ค้นหาชื่อ โทรศัพท์ หรืออีเมล", "Seat capacity is full.": "จำนวนผู้ใช้เต็มตามแผนแล้ว",
  "Select": "เลือก", "Select a conversation": "เลือกการสนทนา", "Select at least two.": "เลือกอย่างน้อยสองรายการ", "Select contact": "เลือกข้อมูลติดต่อ",
  "Select product": "เลือกผลิตภัณฑ์", "Selected conversation": "การสนทนาที่เลือก", "Self-serve": "ดำเนินการด้วยตนเอง",
  "Send invitation": "ส่งคำเชิญ", "Send update": "ส่งข้อมูลอัปเดต", "Sessions / turns": "เซสชัน / ช่วงสนทนา", "Settled minutes": "นาทีที่หักโควตาแล้ว",
  "Setup and Enterprise services": "บริการติดตั้งและบริการ Enterprise", "Setup guides": "คู่มือการตั้งค่า",
  "Setup guides appear when a product subscription is available in this workspace.": "คู่มือการตั้งค่าจะแสดงเมื่อเวิร์กสเปซนี้มีสิทธิ์ใช้ผลิตภัณฑ์",
  "Setup key": "Setup key", "Setup steps": "ขั้นตอนการตั้งค่า", "Signed-in devices": "อุปกรณ์ที่เข้าสู่ระบบ",
  "Social channels": "ช่องทางโซเชียล", "Social connections could not be loaded": "โหลดการเชื่อมต่อช่องทางโซเชียลไม่สำเร็จ",
  "Source": "แหล่งข้อมูล", "Source library": "รายการแหล่งข้อมูล", "Step": "ขั้นตอน", "Step A": "ขั้นตอน A", "Step D": "ขั้นตอน D",
  "Step E": "ขั้นตอน E", "Step F": "ขั้นตอน F", "Steps B–C": "ขั้นตอน B–C", "Structured recommendations": "คำแนะนำแบบมีโครงสร้าง",
  "Submit connector": "ส่งตัวเชื่อมต่อ", "Submit request": "ส่งคำขอ", "Submitted jobs appear here.": "งานที่ส่งแล้วจะแสดงที่นี่",
  "Subscription, payment, cancellation and credit events will appear here.": "เหตุการณ์สมัครใช้บริการ ชำระเงิน ยกเลิก และเครดิตจะแสดงที่นี่",
  "Suggestions only": "เป็นเพียงคำแนะนำ", "Support access status unavailable": "โหลดสถานะสิทธิ์ช่วยเหลือไม่สำเร็จ", "THB": "บาท",
  "Tags": "แท็ก", "Tags and attributes": "แท็กและแอตทริบิวต์", "Take over": "รับช่วงการสนทนา", "Template": "เทมเพลต",
  "Tenant Master Admin access required": "ต้องมีสิทธิ์ผู้ดูแลหลักของเวิร์กสเปซ", "Terminal reasons": "เหตุผลที่สิ้นสุด", "Test Call": "ทดสอบการโทร",
  "Text": "ข้อความ", "Thai automated-agent disclosure": "ข้อความภาษาไทยที่แจ้งว่าเป็นระบบอัตโนมัติ", "Thai disclosure": "ข้อความแจ้งผู้ใช้ภาษาไทย",
  "Thai follow-up message": "ข้อความติดตามภาษาไทย", "Thai label": "ป้ายกำกับภาษาไทย", "Thai offline message": "ข้อความนอกเวลาภาษาไทย",
  "English automated-agent disclosure": "ข้อความภาษาอังกฤษที่แจ้งว่าเป็นระบบอัตโนมัติ", "English disclosure": "ข้อความแจ้งผู้ใช้ภาษาอังกฤษ",
  "English follow-up message": "ข้อความติดตามภาษาอังกฤษ", "English label": "ป้ายกำกับภาษาอังกฤษ", "English offline message": "ข้อความนอกเวลาภาษาอังกฤษ",
  "Timed follow-up": "ติดตามตามเวลาที่กำหนด", "Title": "ชื่อเรื่อง", "Top customer questions": "คำถามยอดนิยมของลูกค้า",
  "Transcript retention": "ระยะเวลาเก็บข้อความการสนทนา", "Transfer & Callback": "ส่งต่อและติดต่อกลับ", "Transfer ownership": "โอนสิทธิ์เจ้าของ",
  "Try again before choosing a plan.": "ลองใหม่ก่อนเลือกแผน", "Turn failures": "ช่วงสนทนาที่ล้มเหลว", "UTC calendar days": "วันตามปฏิทิน UTC",
  "Unanswered inputs": "ข้อความที่ยังไม่ได้ตอบ", "Understand what your workspace is using": "ทำความเข้าใจการใช้งานของเวิร์กสเปซ",
  "Unknown": "ยังไม่ทราบ", "Update cap": "อัปเดตขีดจำกัด", "Update for the delivery team": "ข้อมูลอัปเดตสำหรับทีมดำเนินงาน",
  "Upgrade to AI Chat Premium to connect LINE.": "อัปเกรดเป็น AI Chat Premium เพื่อเชื่อมต่อ LINE",
  "Upgrade to AI Chat Premium to connect Messenger.": "อัปเกรดเป็น AI Chat Premium เพื่อเชื่อมต่อ Messenger",
  "Upgrade to AI Chat Premium to connect WhatsApp.": "อัปเกรดเป็น AI Chat Premium เพื่อเชื่อมต่อ WhatsApp",
  "Upload PDF, DOCX or TXT": "อัปโหลด PDF, DOCX หรือ TXT", "Upload document": "อัปโหลดเอกสาร", "Usage alerts": "การแจ้งเตือนการใช้งาน",
  "Usage anomaly": "การใช้งานผิดปกติ", "Usage is shown in customer-friendly units. Internal processing and provider details are never included.": "แสดงการใช้งานด้วยหน่วยที่ลูกค้าเข้าใจง่าย โดยไม่รวมรายละเอียดการประมวลผลภายในหรือผู้ให้บริการ",
  "Usage is temporarily unavailable": "ข้อมูลการใช้งานไม่พร้อมชั่วคราว", "Used when a conversation needs human assistance.": "ใช้เมื่อการสนทนาต้องการความช่วยเหลือจากทีมงาน",
  "Validated at commit time": "ตรวจสอบความถูกต้องขณะบันทึก", "Value": "ค่า", "Verify MFA": "ยืนยัน MFA", "Verify install": "ตรวจสอบการติดตั้ง",
  "Verify token": "Verify token", "View launch checklist": "ดูรายการตรวจสอบก่อนเปิดใช้", "View-only access": "สิทธิ์ดูอย่างเดียว",
  "View-only access does not include sending replies.": "สิทธิ์ดูอย่างเดียวไม่สามารถส่งข้อความตอบกลับ", "Voice & Languages": "เสียงและภาษา",
  "Voice Agent Studio": "สตูดิโอ Voice Agent", "Voice Agent Studio sections": "ส่วนต่าง ๆ ในสตูดิโอ Voice Agent", "Voice Agent summary": "สรุป Voice Agent",
  "Voice agent name": "ชื่อ Voice Agent", "Voice call outcome": "ผลลัพธ์ของสาย", "Voice engine availability": "สถานะพร้อมใช้ของระบบเสียง",
  "Voice privacy": "ความเป็นส่วนตัวของระบบเสียง", "Voice recording": "การบันทึกเสียง", "Voice recording status": "สถานะการบันทึกเสียง",
  "We couldn’t load": "โหลดไม่สำเร็จ", "We couldn’t load your workspace": "โหลดเวิร์กสเปซไม่สำเร็จ", "Website automation": "ระบบอัตโนมัติบนเว็บไซต์",
  "Website deployments": "การติดตั้งบนเว็บไซต์", "Website origins": "ต้นทางเว็บไซต์", "Weekly": "รายสัปดาห์",
  "WhatsApp connections": "การเชื่อมต่อ WhatsApp", "Withdrawn": "ถอนคำขอแล้ว", "Workspace": "เวิร์กสเปซ",
  "Workspace address": "ที่อยู่เวิร์กสเปซ", "Workspace invitation": "คำเชิญเข้าเวิร์กสเปซ", "Workspace members": "สมาชิกเวิร์กสเปซ",
  "Workspace operations": "การดำเนินงานเวิร์กสเปซ", "Workspace overview": "ภาพรวมเวิร์กสเปซ", "Workspace ownership": "สิทธิ์เจ้าของเวิร์กสเปซ",
  "Workspace page unavailable": "หน้าเวิร์กสเปซไม่พร้อมใช้งาน", "Workspace slug:": "ชื่อท้าย URL ของเวิร์กสเปซ:", "Workspace-wide / Enterprise": "ทั้งเวิร์กสเปซ / Enterprise",
  "Write a reply": "เขียนข้อความตอบกลับ", "Yes / No": "ใช่ / ไม่", "You don’t have access to this area": "คุณไม่มีสิทธิ์เข้าถึงส่วนนี้",
  "You can review approved business content. A workspace administrator can add sources.": "คุณดูเนื้อหาธุรกิจที่อนุมัติแล้วได้ ผู้ดูแลเวิร์กสเปซเป็นผู้เพิ่มแหล่งข้อมูล",
  "You can review conversations and outcomes. An operator or administrator can take over and reply.": "คุณดูการสนทนาและผลลัพธ์ได้ ผู้ปฏิบัติงานหรือผู้ดูแลเป็นผู้รับช่วงและตอบกลับ",
  "You can review customer records. An operator or administrator can create contacts.": "คุณดูข้อมูลลูกค้าได้ ผู้ปฏิบัติงานหรือผู้ดูแลเป็นผู้สร้างข้อมูลติดต่อ",
  "You can review launch progress. A workspace administrator can refresh the evidence after setup or testing.": "คุณดูความคืบหน้าก่อนเปิดใช้ได้ ผู้ดูแลเวิร์กสเปซเป็นผู้รีเฟรชหลักฐานหลังตั้งค่าหรือทดสอบ",
  "You can review setup progress and active services. A workspace administrator can request add-ons or professional services.": "คุณดูความคืบหน้าการตั้งค่าและบริการที่ใช้งานได้ ผู้ดูแลเวิร์กสเปซเป็นผู้ขอส่วนเสริมหรือบริการจากผู้เชี่ยวชาญ",
  "You can review the business profile. An administrator can update it.": "คุณดูโปรไฟล์ธุรกิจได้ ผู้ดูแลเป็นผู้แก้ไข",
  "You can review the sales pipeline. An operator or administrator can create leads.": "คุณดูขั้นตอนงานขายได้ ผู้ปฏิบัติงานหรือผู้ดูแลเป็นผู้สร้างข้อมูลผู้สนใจ",
  "Your account and saved data have not changed. Check your connection and try again.": "บัญชีและข้อมูลที่บันทึกไว้ไม่ถูกเปลี่ยน โปรดตรวจการเชื่อมต่อแล้วลองใหม่",
  "Your account session could not be checked. No ownership state changed.": "ตรวจสอบเซสชันบัญชีไม่สำเร็จ และไม่มีการเปลี่ยนสิทธิ์เจ้าของ",
  "Your account session could not be checked. No workspace access changed.": "ตรวจสอบเซสชันบัญชีไม่สำเร็จ และไม่มีการเปลี่ยนสิทธิ์เวิร์กสเปซ",
  "Your current workspace role does not include this permission. Ask a workspace owner to change your role if you need access.": "บทบาทปัจจุบันไม่มีสิทธิ์นี้ หากจำเป็นต้องใช้งาน โปรดขอเจ้าของเวิร์กสเปซเปลี่ยนบทบาทให้",
  "Your last action may not have completed. Try again before repeating a change, or return to the workspace overview.": "การดำเนินการล่าสุดอาจยังไม่สำเร็จ โปรดลองใหม่ก่อนทำรายการซ้ำ หรือกลับไปหน้าภาพรวมเวิร์กสเปซ",
  "Your plans are unchanged. Try loading this page again.": "แผนของคุณไม่ถูกเปลี่ยน โปรดลองโหลดหน้านี้ใหม่", "Your saved data has not changed. Check your connection and try again.": "ข้อมูลที่บันทึกไว้ไม่ถูกเปลี่ยน โปรดตรวจการเชื่อมต่อแล้วลองใหม่",
  "access": "สิทธิ์ใช้งาน", "active": "ใช้งานอยู่", "active add-ons": "ส่วนเสริมที่ใช้งานอยู่", "appointments": "นัดหมาย",
  "approved": "อนุมัติแล้ว", "catalogue items": "รายการในแค็ตตาล็อก", "channel units attempted": "หน่วยช่องทางที่พยายามส่ง",
  "committed": "ยืนยันแล้ว", "completed": "เสร็จสิ้น", "consent": "ความยินยอม", "currently reserved": "ที่จองใช้อยู่",
  "delivered": "ส่งแล้ว", "deployments": "การติดตั้ง", "engagements": "งานบริการ", "executions": "การทำงาน", "handovers": "การส่งต่อ",
  "knowledge pins": "ความรู้ที่ตรึงไว้", "lead": "ผู้สนใจ", "may match": "อาจเป็นรายการเดียวกัน", "metered responses": "คำตอบที่นับการใช้งาน",
  "min": "นาที", "nodes": "โนด", "origins": "ต้นทาง", "pinned": "ตรึงแล้ว", "playbook": "คู่มือ", "remaining": "คงเหลือ",
  "requested": "ส่งคำขอแล้ว", "seats": "จำนวนผู้ใช้", "sessions /": "เซสชัน /", "sources": "แหล่งข้อมูล", "unread": "ยังไม่อ่าน", "used": "ใช้แล้ว",
  "(reason required when enabling).": "(ต้องระบุเหตุผลเมื่อเปิดใช้งาน)", "-day": " วัน", "/ revision": "/ ฉบับ",
  "12 hours": "12 ชั่วโมง", "24 hours": "24 ชั่วโมง", "48 hours": "48 ชั่วโมง", "6 hours": "6 ชั่วโมง", "7 days": "7 วัน", "72 hours": "72 ชั่วโมง",
  "95th percentile response": "เวลาตอบสนองเปอร์เซ็นไทล์ที่ 95", "A product appears here after its subscription request is created. Public charging remains disabled until the commercial release gate is approved.": "ผลิตภัณฑ์จะแสดงที่นี่หลังสร้างคำขอสมัครใช้บริการ ระบบยังไม่เรียกเก็บเงินสาธารณะจนกว่าประตูอนุมัติการเปิดขายจะผ่านครบถ้วน",
  "Default weekday hours Mon–Fri 09:00–17:00 are saved with the profile when Flow Bot schedules are available. Inbox handover teams can be refined in the full studio later.": "เมื่อระบบตาราง FlowBot พร้อมใช้ โปรไฟล์จะบันทึกเวลาทำการเริ่มต้นวันจันทร์–ศุกร์ 09:00–17:00 และสามารถปรับทีมรับช่วงการสนทนาในสตูดิโอภายหลัง",
  "English": "English", "English and Thai recognition, latency, interruption, silence, noise, reconnect, callback, and handover still require restricted staging evaluation against approved thresholds.": "การรู้จำภาษาอังกฤษและไทย เวลาแฝง การพูดแทรก ความเงียบ เสียงรบกวน การเชื่อมต่อใหม่ การติดต่อกลับ และการส่งต่อ ยังต้องผ่านการประเมินในระบบทดสอบแบบจำกัดตามเกณฑ์ที่อนุมัติ",
  "Erasure anonymizes the contact but skips transcript redaction for held conversations. Set or clear holds with recent authentication via": "การลบข้อมูลจะทำให้ข้อมูลติดต่อไม่ระบุตัวตน แต่จะไม่แก้ไขข้อความของการสนทนาที่ถูกระงับการลบ ตั้งค่าหรือยกเลิกการระงับด้วยการยืนยันตัวตนล่าสุดผ่าน",
  "Every action is revalidated against the active subscription and allow-list inside the same database transaction as the transcript response.": "ทุกการดำเนินการจะตรวจสอบซ้ำกับสิทธิ์สมัครใช้บริการและรายการที่อนุญาต ภายในธุรกรรมฐานข้อมูลเดียวกับคำตอบการสนทนา",
  "Expired message and Voice turn content is replaced with a non-personal audit tombstone. Call outcome metadata remains for operational reporting. Voice recording remains disabled.": "ข้อความและเนื้อหาช่วงสนทนาด้วยเสียงที่หมดอายุจะถูกแทนด้วยหลักฐานตรวจสอบที่ไม่ระบุตัวบุคคล ข้อมูลผลลัพธ์ของสายยังคงไว้เพื่อรายงานการทำงาน และยังปิดการบันทึกเสียง",
  "Finish or repair the Advanced JSON before using the guided fields. Your JSON text is preserved.": "กรอกหรือแก้ไข JSON ขั้นสูงให้สมบูรณ์ก่อนใช้ช่องตั้งค่าแบบแนะนำ ข้อความ JSON ของคุณจะยังคงอยู่",
  "For expert use. Leaving this field validates the complete Sales Core playbook before guided editing resumes.": "สำหรับผู้เชี่ยวชาญ เมื่อออกจากช่องนี้ระบบจะตรวจคู่มือ Sales Core ทั้งหมดก่อนกลับไปแก้ไขแบบแนะนำ",
  "Guided LINE connect (Channel ID + Channel Secret only)": "ตัวช่วยเชื่อมต่อ LINE (ใช้เฉพาะ Channel ID และ Channel Secret)",
  "Install verification status could not be loaded. Deployment records remain available.": "โหลดสถานะตรวจสอบการติดตั้งไม่สำเร็จ แต่ข้อมูลการติดตั้งยังคงอยู่",
  "LINE account reference": "รหัสอ้างอิงบัญชี LINE", "LINE connections": "การเชื่อมต่อ LINE", "Last 14 days shown · full period in CSV": "แสดง 14 วันล่าสุด · ดูทั้งรอบในไฟล์ CSV",
  "Matching email or phone values never merge customer records automatically. Review these records before any future audited merge workflow.": "อีเมลหรือโทรศัพท์ที่ตรงกันจะไม่รวมข้อมูลลูกค้าโดยอัตโนมัติ โปรดตรวจสอบก่อนใช้กระบวนการรวมข้อมูลที่มีหลักฐานกำกับในอนาคต",
  "Metering is active for pilot visibility, but no public allowance or overage promise has been published.": "ระบบกำลังวัดการใช้งานสำหรับโครงการนำร่อง แต่ยังไม่ได้เผยแพร่โควตาหรือเงื่อนไขการใช้เกินโควตาต่อสาธารณะ",
  "Operational analytics do not replace the production quality gate.": "ข้อมูลวิเคราะห์การทำงานไม่ทดแทนเกณฑ์คุณภาพก่อนเปิดใช้งานจริง",
  "Progress comes from server-verified workspace and product evidence. A browser cannot mark setup ready by choosing a stage.": "ความคืบหน้าอ้างอิงหลักฐานเวิร์กสเปซและผลิตภัณฑ์ที่เซิร์ฟเวอร์ตรวจสอบ การเลือกขั้นตอนในเบราว์เซอร์ไม่สามารถทำเครื่องหมายว่าพร้อมได้",
  "Progress is computed from server evidence on Overview. These links open the real product setup — they do not mark a guide complete by themselves.": "ระบบคำนวณความคืบหน้าจากหลักฐานบนเซิร์ฟเวอร์ในหน้าภาพรวม ลิงก์เหล่านี้เปิดการตั้งค่าผลิตภัณฑ์จริง แต่ไม่ทำให้คู่มือเสร็จสิ้นโดยอัตโนมัติ",
  "Public rollout still requires the applicable product, legal, commercial, and operational release gates.": "การเปิดให้บริการสาธารณะยังต้องผ่านเกณฑ์ด้านผลิตภัณฑ์ กฎหมาย การค้า และการดำเนินงานที่เกี่ยวข้อง",
  "Recording remains disabled until consent, jurisdiction, retention, erasure, and legal review are configured and accepted.": "ระบบจะปิดการบันทึกไว้จนกว่าจะตั้งค่าและอนุมัติเรื่องความยินยอม เขตอำนาจกฎหมาย การเก็บรักษา การลบข้อมูล และการตรวจสอบทางกฎหมาย",
  "Return here and refresh evidence. Install checks alone do not set launch ready.": "กลับมาที่หน้านี้แล้วรีเฟรชหลักฐาน การตรวจการติดตั้งเพียงอย่างเดียวไม่ทำให้ระบบพร้อมเปิดใช้",
  "Run the installed widget on an approved origin. Test sessions consume reserved minutes and create real transcript/action evidence; use staging contact details only.": "เรียกใช้วิดเจ็ตที่ติดตั้งบนต้นทางที่อนุมัติ เซสชันทดสอบจะใช้โควตานาทีและสร้างหลักฐานข้อความกับการดำเนินการจริง จึงควรใช้ข้อมูลติดต่อสำหรับทดสอบเท่านั้น",
  "Second-Generation activation is pending internal route qualification.": "การเปิดใช้ระบบรุ่นที่สองกำลังรอการรับรองเส้นทางภายใน",
  "Selecting a plan saves a server-side preference. Access activates after successful payment — not from email verification or this browser alone.": "การเลือกแผนจะบันทึกความสนใจบนเซิร์ฟเวอร์ สิทธิ์จะเปิดหลังชำระเงินสำเร็จ ไม่ได้เปิดจากการยืนยันอีเมลหรือเบราว์เซอร์นี้เพียงอย่างเดียว",
  "The definition must be valid FlowBot JSON with a nodes map. Advanced JSON remains open so you can repair it.": "การตั้งค่าต้องเป็น FlowBot JSON ที่ถูกต้องและมีแผนที่ nodes ส่วน JSON ขั้นสูงจะยังเปิดไว้ให้แก้ไข",
  "The deployment can be prepared now, but calls return neutral unavailability until a reviewed Gen2 route is active. It will never fall back to First-Generation.": "เตรียมการติดตั้งได้แล้ว แต่ระบบจะแจ้งว่าไม่พร้อมใช้งานอย่างเป็นกลางจนกว่าเส้นทาง Gen2 ที่ผ่านการตรวจจะเปิดใช้ และจะไม่ย้อนกลับไปใช้ระบบรุ่นแรก",
  "The full key is never stored or displayed again.": "ระบบจะไม่เก็บหรือแสดงกุญแจฉบับเต็มอีกครั้ง",
  "The link may be outdated or unavailable for this address. No customer or workspace record has been changed.": "ลิงก์อาจหมดอายุหรือใช้ไม่ได้กับที่อยู่นี้ ข้อมูลลูกค้าและเวิร์กสเปซยังไม่ถูกเปลี่ยน",
  "These details are required before technical launch readiness can complete. Changes are saved on the server and reflected after the checklist refreshes.": "ต้องกรอกรายละเอียดเหล่านี้ก่อนผ่านความพร้อมด้านเทคนิค การเปลี่ยนแปลงจะบันทึกบนเซิร์ฟเวอร์และแสดงหลังรีเฟรชรายการตรวจสอบ",
  "This conversation is closed.": "การสนทนานี้ปิดแล้ว", "This workspace page does not exist.": "ไม่พบหน้าเวิร์กสเปซนี้", "This workspace page needs another try.": "โปรดลองโหลดหน้าเวิร์กสเปซนี้อีกครั้ง",
  "Use this callback URL and the verify token entered above, subscribe to messages and messaging events, then run a health check.": "ใช้ callback URL นี้กับ verify token ที่กรอกด้านบน สมัครรับ messages และ messaging events แล้วตรวจสถานะ",
  "Use this callback URL and the verify token entered above, subscribe to messages, then run a health check.": "ใช้ callback URL นี้กับ verify token ที่กรอกด้านบน สมัครรับ messages แล้วตรวจสถานะ",
  "before inviting another member.": "ก่อนเชิญสมาชิกเพิ่ม", "for first launch. Studio tabs below are for day-2 editing.": "สำหรับการเปิดใช้ครั้งแรก ส่วนแท็บสตูดิโอด้านล่างใช้ปรับแต่งหลังเปิดใช้",
  "to see every branch labelled, which endings are calls to action, and unreachable or loop warnings. The list editor below stays the place to make changes.": "เพื่อดูป้ายกำกับทุกทางแยก จุดสิ้นสุดที่มีคำกระตุ้นให้ดำเนินการ และคำเตือนเส้นทางที่เข้าไม่ถึงหรือวนซ้ำ การแก้ไขยังทำผ่านตัวแก้ไขแบบรายการด้านล่าง",
  ", effective": ", มีผลวันที่", "and": "และ", "Versions": "เวอร์ชัน", "10 MB max": "ขนาดไม่เกิน 10 MB",
  "20 / minute": "20 ครั้ง / นาที", "citations /": "การอ้างอิง /", "completed /": "เสร็จสิ้น /", "leads /": "ผู้สนใจ /",
  "FlowBot Basic": "FlowBot Basic", "LINE Official Account": "บัญชี LINE Official Account",
  "DJBOT keeps the conversation moving from the first message to the handover: structured FlowBot journeys, AI TextBot replies drawn from your own business knowledge, captured lead details, and human takeover in a shared inbox.": "DJBOT ช่วยให้การสนทนาดำเนินต่อเนื่องตั้งแต่ข้อความแรกจนถึงการส่งต่อ ด้วยเส้นทาง FlowBot ที่เป็นระบบ คำตอบจาก AI TextBot ที่อ้างอิงความรู้ของธุรกิจ การบันทึกข้อมูลผู้สนใจ และการรับช่วงโดยทีมงานในกล่องข้อความร่วม",
  "DJBOT lead conversion workspace preview": "ตัวอย่างเวิร์กสเปซ DJBOT สำหรับเปลี่ยนผู้สนใจเป็นลูกค้า",
  "FlowBot asked the qualifying questions, saved the customer's details as a lead, and passed the conversation to a person when it was needed.": "FlowBot ถามคำถามเพื่อคัดกรอง บันทึกข้อมูลลูกค้าเป็นผู้สนใจ และส่งต่อการสนทนาให้ทีมงานเมื่อจำเป็น",
  "For privacy, the result is the same whether or not an account exists.": "เพื่อความเป็นส่วนตัว ระบบจะแสดงผลเหมือนกันไม่ว่าจะมีบัญชีนี้อยู่หรือไม่",
  "Check the documented endpoint and request method. No account, workspace, or service record has been changed.": "ตรวจสอบ endpoint และ method ตามเอกสาร ไม่มีการเปลี่ยนแปลงบัญชี เวิร์กสเปซ หรือข้อมูลบริการ",
  "API information": "ข้อมูล API", "Endpoint not found": "ไม่พบ endpoint", "Service endpoint": "endpoint ของบริการ",
  "Service page unavailable": "หน้าบริการไม่พร้อมใช้งาน", "The service page needs another try.": "โหลดหน้าบริการไม่สำเร็จ โปรดลองอีกครั้ง",
  "This API page does not exist.": "ไม่มีหน้า API นี้", "Return to API information": "กลับไปยังข้อมูล API",
  "Retry this page or return to the API information surface. Client applications should follow the endpoint's documented error contract.": "ลองโหลดหน้านี้อีกครั้งหรือกลับไปยังหน้าข้อมูล API แอปพลิเคชันที่เรียกใช้ควรจัดการข้อผิดพลาดตามสัญญาที่ระบุไว้ในเอกสาร endpoint",
  "DJAY Bot API": "API ของ DJAY Bot",
  "Authenticator QR code": "คิวอาร์โค้ดสำหรับแอปยืนยันตัวตน",
  "sales_team": "ทีมขาย",

  "1 hour": "1 ชั่วโมง", "2 hours": "2 ชั่วโมง", "30 minutes": "30 นาที", "4 hours": "4 ชั่วโมง",
  "1. Propose route": "1. เสนอเส้นทาง", "2. Independent qualification": "2. ตรวจรับรองโดยผู้ตรวจอิสระ",
  "3. Request canary": "3. ขอทดสอบแบบ Canary", "4. Production admission": "4. อนุมัติเข้าสู่ระบบจริง",
  "24-hour evidence required": "ต้องมีหลักฐานย้อนหลัง 24 ชั่วโมง", "A release remains fail-closed until all seven service objectives, nine time-limited operational attestations, incident review, usage reconciliation, and live registration authority pass together.": "ระบบจะยังไม่อนุญาตให้เปิดใช้ จนกว่าเป้าหมายบริการทั้ง 7 ข้อ หลักฐานรับรองการปฏิบัติงานแบบมีอายุทั้ง 9 รายการ การทบทวนเหตุขัดข้อง การกระทบยอดการใช้งาน และสิทธิ์ลงทะเบียนระบบจริงจะผ่านพร้อมกัน",
  "Public release readiness": "ความพร้อมเปิดให้บริการสาธารณะ", "Release operations": "การดำเนินงานเพื่อเปิดใช้",
  "Checking release readiness…": "กำลังตรวจสอบความพร้อมเปิดใช้…", "Release evidence unavailable": "โหลดหลักฐานความพร้อมเปิดใช้ไม่ได้",
  "The release gate is blocked. No service should be promoted while current evidence cannot be verified.": "เกณฑ์อนุมัติการเปิดใช้ยังไม่ผ่าน ห้ามเลื่อนบริการขึ้นระบบจริงขณะที่ตรวจสอบหลักฐานปัจจุบันไม่ได้",
  "Retry readiness check": "ตรวจสอบความพร้อมอีกครั้ง", "Service objectives": "เป้าหมายระดับบริการ", "Attestations": "หลักฐานรับรอง",
  "Blocking incidents": "เหตุขัดข้องที่ขัดขวางการเปิดใช้", "Usage ledger": "บัญชีรายการการใช้งาน", "Registration authority": "สิทธิ์อนุมัติการลงทะเบียน",
  "current": "ปัจจุบัน", "passing": "ผ่าน", "major or critical": "ระดับร้ายแรงหรือวิกฤต", "MFA status": "สถานะ MFA",
  "Platform users": "ผู้ใช้แพลตฟอร์ม", "SME tenants": "ลูกค้าธุรกิจ SME", "Subscriptions": "การสมัครใช้บริการ",
  "Pending activation": "รอเปิดใช้งาน", "System evidence": "หลักฐานจากระบบ",
  "Review current identity, release, and role-authorized operations data": "ตรวจสอบข้อมูลตัวตน การเปิดใช้ และการดำเนินงานตามสิทธิ์ของบทบาท",
  "Loading current SLO, incident, on-call, restore, replay, queue, pool, security, privacy, support, and usage evidence.": "กำลังโหลดหลักฐาน SLO เหตุขัดข้อง เวรรับผิดชอบ การกู้ระบบ การเล่นซ้ำ คิว พูล ความปลอดภัย ความเป็นส่วนตัว การสนับสนุน และการใช้งาน",
  "Internal operations": "การดำเนินงานภายใน", "Platform health": "สุขภาพระบบแพลตฟอร์ม",
  "Checking platform session...": "กำลังตรวจสอบเซสชันแพลตฟอร์ม…", "Platform operations could not be loaded": "โหลดข้อมูลการดำเนินงานแพลตฟอร์มไม่สำเร็จ",
  "Your access and operational data have not changed. Check the internal service connection and try again.": "สิทธิ์และข้อมูลการดำเนินงานของคุณไม่เปลี่ยนแปลง โปรดตรวจการเชื่อมต่อบริการภายในแล้วลองใหม่",
  "Refreshing authorized operations data…": "กำลังรีเฟรชข้อมูลการดำเนินงานที่ได้รับอนุญาต…",
  "Current controls remain unavailable until each requested resource responds.": "ส่วนควบคุมจะยังใช้ไม่ได้จนกว่าทรัพยากรที่ร้องขอทั้งหมดจะตอบกลับ",
  "Some operations data could not be loaded": "โหลดข้อมูลการดำเนินงานบางส่วนไม่สำเร็จ", "No operational state was changed. Unavailable areas:": "ไม่มีการเปลี่ยนสถานะการดำเนินงาน ส่วนที่ไม่พร้อมใช้งาน:",
  "Billing operations · restricted": "การดำเนินงานด้านการเรียกเก็บเงิน · จำกัดสิทธิ์", "Checking usage reconciliation…": "กำลังตรวจสอบการกระทบยอดการใช้งาน…",
  "Comparing customer-unit balances with reservation and immutable event evidence.": "กำลังเปรียบเทียบยอดหน่วยใช้งานของลูกค้ากับการจองและหลักฐานเหตุการณ์ที่แก้ไขไม่ได้",
  "Usage reconciliation unavailable": "ข้อมูลกระทบยอดการใช้งานไม่พร้อม", "Retry reconciliation": "กระทบยอดอีกครั้ง",
  "No balance or billing state was changed. Treat the gate as not reconciled until the evidence can be loaded.": "ไม่มีการเปลี่ยนยอดคงเหลือหรือสถานะเรียกเก็บเงิน ให้ถือว่าเกณฑ์นี้ยังไม่ผ่านการกระทบยอดจนกว่าจะโหลดหลักฐานได้",
  "Usage reconciliation": "การกระทบยอดการใช้งาน", "Customer-unit balances are checked against open reservations and immutable settlement events. This is operational evidence only; it does not enable charging or create invoice authority.": "ระบบตรวจยอดหน่วยใช้งานของลูกค้ากับรายการจองที่ยังเปิดและเหตุการณ์ชำระบัญชีที่แก้ไขไม่ได้ ข้อมูลนี้เป็นหลักฐานการดำเนินงานเท่านั้น ไม่ได้เปิดการเรียกเก็บเงินหรือให้อำนาจออกใบแจ้งหนี้",
  "Accounts checked": "บัญชีที่ตรวจสอบ", "reconciled": "กระทบยอดแล้ว", "Needs attention": "ต้องตรวจสอบ", "balance or event variance": "ยอดหรือเหตุการณ์ไม่ตรงกัน",
  "Missing current account": "ไม่พบบัญชีรอบปัจจุบัน", "active subscriptions": "การสมัครใช้บริการที่ใช้งานอยู่", "Unmapped events": "เหตุการณ์ที่ยังไม่จับคู่",
  "period mapping required": "ต้องจับคู่รอบบัญชี", "Expired reservations": "การจองที่หมดอายุ", "past-period open records": "รายการรอบก่อนที่ยังเปิดอยู่",
  "Provider attention": "ต้องตรวจสอบข้อมูลผู้ให้บริการ", "open cases": "กรณีที่ยังเปิด", "Finance review": "การตรวจสอบโดยฝ่ายการเงิน",
  "Read-only evidence. Escalate a variance; never repair immutable usage or quota totals with direct SQL.": "หลักฐานนี้ดูได้อย่างเดียว หากพบความคลาดเคลื่อนให้ยกระดับตรวจสอบ ห้ามแก้ยอดการใช้งานหรือโควตาที่แก้ไขไม่ได้ด้วย SQL โดยตรง",
  "Usage reconciliation accounts": "บัญชีสำหรับกระทบยอดการใช้งาน", "No quota accounts to reconcile": "ไม่มีบัญชีโควตาที่ต้องกระทบยอด",
  "Showing the": "กำลังแสดง", "highest-priority accounts. Aggregate checks cover all": "บัญชีที่มีลำดับความสำคัญสูงสุด โดยการตรวจแบบรวมครอบคลุมทั้งหมด", "accounts.": "บัญชี",
  "Provider usage reconciliation attention": "รายการกระทบยอดการใช้งานจากผู้ให้บริการที่ต้องตรวจสอบ", "Request provider credit": "ขอเครดิตจากผู้ให้บริการ",
  "Correct correlation": "แก้ไขการจับคู่", "Accept provider-only event": "ยอมรับเหตุการณ์ที่มีเฉพาะฝั่งผู้ให้บริการ", "No provider correlation failures": "ไม่พบข้อผิดพลาดในการจับคู่ข้อมูลผู้ให้บริการ",
  "Finance operations · restricted": "การดำเนินงานการเงิน · จำกัดสิทธิ์", "Stripe invoice reconciliation": "การกระทบยอดใบแจ้งหนี้ Stripe",
  "Immutable invoice evidence is compared with independently retrieved Stripe invoice state. Remediation requires a separate finance reviewer.": "ระบบเปรียบเทียบหลักฐานใบแจ้งหนี้ที่แก้ไขไม่ได้กับสถานะใบแจ้งหนี้ Stripe ที่ดึงมาแยกต่างหาก การแก้ไขต้องมีผู้ตรวจฝ่ายการเงินอีกคน",
  "exact normalized state": "สถานะมาตรฐานที่ตรงกัน", "provider snapshots": "ภาพสถานะจากผู้ให้บริการ", "review required": "ต้องตรวจสอบ",
  "Invoice": "ใบแจ้งหนี้", "Reconciled": "กระทบยอดแล้ว", "Request Stripe correction": "ขอให้แก้ไขข้อมูล Stripe", "Issue customer credit": "ออกเครดิตให้ลูกค้า",
  "No Stripe invoices have been reconciled": "ยังไม่มีใบแจ้งหนี้ Stripe ที่ผ่านการกระทบยอด",
  "Stripe payment, refund and credit reconciliation": "การกระทบยอดการชำระเงิน การคืนเงิน และเครดิตของ Stripe",
  "Payments, refunds and credit notes are independently retrieved and compared with immutable local evidence. Corrections require a separate reviewer.": "ระบบดึงข้อมูลการชำระเงิน การคืนเงิน และใบลดหนี้แยกต่างหากเพื่อเปรียบเทียบกับหลักฐานภายในที่แก้ไขไม่ได้ การแก้ไขต้องมีผู้ตรวจอีกคน",
  "provider events": "เหตุการณ์จากผู้ให้บริการ", "Stripe financial event reconciliation": "การกระทบยอดเหตุการณ์ทางการเงินของ Stripe",
  "No payment, refund or credit evidence has been reconciled": "ยังไม่มีหลักฐานการชำระเงิน การคืนเงิน หรือเครดิตที่ผ่านการกระทบยอด",
  "FlowAccount reconciliation": "การกระทบยอด FlowAccount", "Daily remote evidence is compared with immutable local invoices and credits. Provider state cannot overwrite the local accounting ledger.": "ระบบเปรียบเทียบหลักฐานรายวันจากภายนอกกับใบแจ้งหนี้และเครดิตภายในที่แก้ไขไม่ได้ สถานะจากผู้ให้บริการไม่สามารถเขียนทับบัญชีแยกประเภทภายใน",
  "remote snapshots": "ภาพสถานะจากภายนอก", "exact local evidence": "หลักฐานภายในที่ตรงกัน", "reference pending": "รอข้อมูลอ้างอิง",
  "Request FlowAccount correction": "ขอแก้ไขข้อมูล FlowAccount", "Credit and replace": "ออกเครดิตและสร้างเอกสารทดแทน", "No FlowAccount documents have been reconciled": "ยังไม่มีเอกสาร FlowAccount ที่ผ่านการกระทบยอด",
  "Billing policy · restricted": "นโยบายเรียกเก็บเงิน · จำกัดสิทธิ์", "Subscription dunning": "การติดตามยอดค้างชำระ", "Enforcement disabled": "ปิดการบังคับใช้อยู่",
  "Payment-failure grace and restriction timing remains disabled until a different Platform Owner approves a versioned policy.": "ยังไม่ใช้ระยะผ่อนผันและกำหนดเวลาจำกัดสิทธิ์เมื่อชำระเงินไม่สำเร็จ จนกว่าเจ้าของแพลตฟอร์มอีกคนจะอนุมัตินโยบายที่มีเวอร์ชัน",
  "Grace period hours": "ระยะผ่อนผัน (ชั่วโมง)", "Restrict after hours": "จำกัดสิทธิ์หลังผ่านไป (ชั่วโมง)", "Notice offsets": "ช่วงเวลาส่งการแจ้งเตือน", "Policy reason": "เหตุผลของนโยบาย",
  "Request policy": "ส่งนโยบายให้อนุมัติ", "Subscription dunning policies": "นโยบายติดตามยอดค้างชำระ", "Notices": "การแจ้งเตือน", "restrict after": "จำกัดสิทธิ์หลัง", "h grace": "ชั่วโมงผ่อนผัน",
  "No dunning policy has been approved": "ยังไม่มีนโยบายติดตามยอดค้างชำระที่อนุมัติแล้ว",
  "Billing recovery · restricted": "การกู้คืนงานเรียกเก็บเงิน · จำกัดสิทธิ์", "Stripe webhook authority": "สิทธิ์จัดการ webhook ของ Stripe",
  "Ignored subscription events are independently retrieved from Stripe. Replay or acceptance requires a different reviewer; payload evidence remains encrypted.": "ระบบดึงเหตุการณ์การสมัครใช้บริการที่ถูกละเว้นจาก Stripe แยกต่างหาก การเล่นซ้ำหรือยอมรับต้องมีผู้ตรวจอีกคน และหลักฐาน payload ยังคงเข้ารหัส",
  "Stripe webhook recovery": "การกู้คืน webhook ของ Stripe", "provider evidence snapshot": "ภาพหลักฐานจากผู้ให้บริการ", "· event …": "· เหตุการณ์ …",
  "Escalate provider": "ยกระดับให้ผู้ให้บริการตรวจสอบ", "Accept unsupported": "ยอมรับเหตุการณ์ที่ไม่รองรับ", "Retry application": "ประมวลผลอีกครั้ง",
  "No ignored Stripe events require recovery": "ไม่มีเหตุการณ์ Stripe ที่ถูกละเว้นและต้องกู้คืน",
  "Runtime admission and recovery": "การอนุมัติระบบรันไทม์และการกู้คืน", "Voice operations": "การดำเนินงานระบบเสียง",
  "Recovery queue": "คิวกู้คืน", "stale connections": "การเชื่อมต่อที่ค้าง", "reconnecting": "กำลังเชื่อมต่อใหม่",
  "Resume admission": "เปิดรับงานอีกครั้ง", "Pause new sessions": "หยุดรับเซสชันใหม่", "Emergency stop": "หยุดฉุกเฉิน", "· changed": "· เปลี่ยนเมื่อ",
  "Second-Generation route governance": "การกำกับเส้นทางระบบรุ่นที่สอง", "Advanced Voice · restricted": "Advanced Voice · จำกัดสิทธิ์",
  "Provider and model identifiers are visible only to Platform Owner and AI Operations. A route stays unavailable until a different reviewer qualifies it and approves a canary; there is no fallback to First-Generation.": "รหัสผู้ให้บริการและโมเดลจะแสดงเฉพาะเจ้าของแพลตฟอร์มและทีมปฏิบัติการ AI เส้นทางจะยังใช้ไม่ได้จนกว่าผู้ตรวจอีกคนจะรับรองและอนุมัติการทดสอบแบบ Canary โดยระบบจะไม่ย้อนกลับไปใช้รุ่นแรก",
  "Second-Generation": "ระบบรุ่นที่สอง", "Profile": "โปรไฟล์", "voice_gen2": "ระบบเสียงรุ่นที่สอง", "qualification required": "ต้องผ่านการรับรอง",
  "Admission": "การอนุมัติเข้าใช้งาน", "Canary": "Canary", "reviewed production traffic": "ทราฟฟิกระบบจริงที่ผ่านการตรวจ", "disabled": "ปิดอยู่",
  "Region key": "รหัสภูมิภาค", "Provider key": "รหัสผู้ให้บริการ", "Model key": "รหัสโมเดล", "Submit candidate": "ส่งตัวเลือกเข้าตรวจสอบ",
  "Proposed candidate": "ตัวเลือกที่เสนอ", "Select candidate": "เลือกตัวเลือก", "Qualification evidence SHA-256": "ค่า SHA-256 ของหลักฐานการรับรอง",
  "Decision": "คำตัดสิน", "Record review": "บันทึกผลการตรวจ", "· another reviewer required": "· ต้องใช้ผู้ตรวจอีกคน",
  "Evaluation evidence SHA-256": "ค่า SHA-256 ของหลักฐานการประเมิน", "Canary percent": "สัดส่วน Canary", "Request change": "ส่งคำขอเปลี่ยนแปลง",
  "Qualified candidate": "ตัวเลือกที่ผ่านการรับรอง", "Start canary": "เริ่ม Canary", "% canary": "% Canary", "Promote": "เลื่อนขึ้นใช้งาน",
  "No routing changes": "ไม่มีการเปลี่ยนเส้นทาง", "Advanced Voice routing changes": "การเปลี่ยนเส้นทาง Advanced Voice",
  "Request admission change": "ขอเปลี่ยนสถานะอนุมัติ", "Requested state": "สถานะที่ขอ", "Enable production traffic": "เปิดทราฟฟิกระบบจริง",
  "Disable production traffic": "ปิดทราฟฟิกระบบจริง", "Acceptance evidence SHA-256": "ค่า SHA-256 ของหลักฐานการยอมรับ", "Acceptance reason": "เหตุผลการยอมรับ",
  "Advanced Voice admission changes": "การเปลี่ยนสถานะอนุมัติ Advanced Voice", "admission": "การอนุมัติ", "No admission changes": "ไม่มีการเปลี่ยนสถานะอนุมัติ",
  "Open and safeguard": "เปิดเหตุขัดข้องและใช้มาตรการป้องกัน", "Incident reason": "สาเหตุเหตุขัดข้อง", "Severity": "ระดับความรุนแรง",
  "Minor · degraded": "เล็กน้อย · ประสิทธิภาพลดลง", "Major · pause": "ร้ายแรง · หยุดชั่วคราว", "Critical · pause": "วิกฤต · หยุดทันที",
  "Related change": "การเปลี่ยนแปลงที่เกี่ยวข้อง", "Credit review required": "ต้องตรวจสอบเครดิต", "No related change": "ไม่มีการเปลี่ยนแปลงที่เกี่ยวข้อง",
  "Open incident": "เปิดเหตุขัดข้อง", "Incident and credit review": "การตรวจเหตุขัดข้องและเครดิต", "Advanced Voice": "Advanced Voice",
  "Resolve": "แก้ไขแล้ว", "Advanced Voice incidents": "เหตุขัดข้อง Advanced Voice", "No Advanced Voice incidents": "ไม่มีเหตุขัดข้อง Advanced Voice",
  "Queue recovery · restricted": "การกู้คืนคิว · จำกัดสิทธิ์", "Checking replay eligibility and independent-review state.": "กำลังตรวจสอบสิทธิ์เล่นซ้ำและสถานะการตรวจโดยผู้ตรวจอิสระ",
  "Loading reviewed recovery": "กำลังโหลดข้อมูลกู้คืนที่ผ่านการตรวจ", "Recovery controls unavailable": "ส่วนควบคุมการกู้คืนไม่พร้อมใช้งาน",
  "Failing closed. Do not use direct SQL; restore the recovery service and retry this read.": "ระบบปิดกั้นเพื่อความปลอดภัย ห้ามใช้ SQL โดยตรง ให้กู้บริการกู้คืนแล้วลองโหลดข้อมูลอีกครั้ง",
  "Retry recovery controls": "โหลดส่วนควบคุมการกู้คืนอีกครั้ง", "Reviewed dead-letter replay": "การเล่นซ้ำรายการ dead letter ที่ผ่านการตรวจ",
  "Only email deliveries with our durable idempotency key are eligible. FlowBot webhooks and social queues remain blocked for root-cause review because an external side effect cannot be proven safe to repeat.": "เฉพาะการส่งอีเมลที่มี idempotency key แบบถาวรเท่านั้นที่มีสิทธิ์เล่นซ้ำ webhook ของ FlowBot และคิวโซเชียลจะยังถูกระงับเพื่อตรวจหาสาเหตุ เพราะยังยืนยันไม่ได้ว่าการทำผลกระทบภายนอกซ้ำจะปลอดภัย",
  "safe email dead letters": "อีเมล dead letter ที่เล่นซ้ำได้อย่างปลอดภัย", "different owner required": "ต้องใช้เจ้าของรายการคนอื่น", "non-idempotent queue classes": "ประเภทคิวที่ทำซ้ำแล้วอาจเกิดผลซ้ำ",
  "Eligible dead letter": "dead letter ที่มีสิทธิ์", "Select an opaque queue item": "เลือกรายการคิวแบบไม่เปิดเผยข้อมูล", "· attempt": "· ครั้งที่ลอง",
  "Root-cause and replay reason": "สาเหตุหลักและเหตุผลที่ขอเล่นซ้ำ", "Cause corrected; approve one idempotent retry": "แก้สาเหตุแล้ว อนุมัติให้ลองซ้ำแบบไม่เกิดผลซ้ำ 1 ครั้ง",
  "Request replay": "ขอเล่นซ้ำ", "No eligible email dead letters": "ไม่มีอีเมล dead letter ที่มีสิทธิ์", "Dead-letter recovery requests": "คำขอกู้คืน dead letter",
  "Approve one retry": "อนุมัติให้ลองซ้ำ 1 ครั้ง", "No recovery requests": "ไม่มีคำขอกู้คืน",
  "Payloads, recipients, tenant identifiers, credentials, providers, and models are never exposed here. Every request and review is immutable audit evidence.": "หน้านี้จะไม่เปิดเผย payload ผู้รับ รหัสลูกค้า ข้อมูลรับรอง ผู้ให้บริการ หรือโมเดล ทุกคำขอและผลตรวจเป็นหลักฐานตรวจสอบที่แก้ไขไม่ได้",
  "inbound queued /": "ขาเข้ารอคิว /", "delivery queued /": "การส่งรอคิว /", "dead letters /": "dead letter /", "failed attempts": "ครั้งที่ล้มเหลว",
  "reauthorization": "การให้อำนาจใหม่", "Social channel health": "สถานะช่องทางโซเชียล", "active /": "ใช้งาน /", "s oldest": "วินาที (รายการเก่าสุด)",
  "Commerce": "การค้า", "Product subscriptions": "การสมัครใช้ผลิตภัณฑ์", "No product subscriptions": "ยังไม่มีการสมัครใช้ผลิตภัณฑ์",
  "Merchant operations": "การดำเนินงานสำหรับร้านค้า", "Add-on and service fulfillment": "การจัดเตรียมส่วนเสริมและบริการ", "open": "เปิดอยู่",
  "Customer requests do not change product access. Add-ons become effective only after reviewed provisioning; professional services become trackable engagements with a named next-action owner.": "คำขอของลูกค้าไม่เปลี่ยนสิทธิ์ผลิตภัณฑ์ ส่วนเสริมจะมีผลหลังผ่านการตรวจและจัดเตรียมแล้ว ส่วนบริการจากผู้เชี่ยวชาญจะถูกติดตามเป็นงานพร้อมผู้รับผิดชอบขั้นตอนถัดไป",
  "Add-on requests": "คำขอส่วนเสริม", "Add-on fulfillment requests": "คำขอจัดเตรียมส่วนเสริม", "· quantity": "· จำนวน", "Provision": "จัดเตรียม",
  "No open add-on requests": "ไม่มีคำขอส่วนเสริมที่เปิดอยู่", "Professional service requests": "คำขอบริการจากผู้เชี่ยวชาญ",
  "Engagement title": "ชื่องานบริการ", "Delivery scope": "ขอบเขตการส่งมอบ", "Shared": "รับผิดชอบร่วมกัน", "Create engagement": "สร้างงานบริการ",
  "No open service requests": "ไม่มีคำขอบริการที่เปิดอยู่", "Active service engagements": "งานบริการที่กำลังดำเนินการ",
  "Active professional service engagements": "งานบริการจากผู้เชี่ยวชาญที่กำลังดำเนินการ", "· next action": "· ขั้นตอนถัดไป",
  "In progress": "กำลังดำเนินการ", "Scheduled": "กำหนดเวลาแล้ว", "Customer-visible update": "ข้อมูลอัปเดตที่ลูกค้าเห็น", "Save update": "บันทึกข้อมูลอัปเดต",
  "No active service engagements": "ไม่มีงานบริการที่กำลังดำเนินการ", "Controlled support": "การสนับสนุนแบบควบคุม",
  "Time-limited tenant access grants": "สิทธิ์เข้าถึงเวิร์กสเปซลูกค้าแบบจำกัดเวลา", "Tenant": "ลูกค้า", "Select tenant": "เลือกลูกค้า", "Reason": "เหตุผล",
  "Support access grants": "สิทธิ์เข้าถึงเพื่อให้การสนับสนุน", "No support access grants": "ไม่มีสิทธิ์เข้าถึงเพื่อให้การสนับสนุน",
  "Restricted access": "พื้นที่จำกัดสิทธิ์", "Platform email": "อีเมลแพลตฟอร์ม", "Multi-factor verification is required.": "ต้องยืนยันตัวตนหลายปัจจัย",
  "Describe verified recovery and remaining safeguards (12–2,000 characters).": "อธิบายการกู้คืนที่ตรวจสอบแล้วและมาตรการป้องกันที่ยังใช้อยู่ (12–2,000 ตัวอักษร)",
  "Resolution for": "การแก้ไขสำหรับ", "incident": "เหตุขัดข้อง", "Save resolution": "บันทึกผลการแก้ไข",
  "Platform page unavailable": "หน้าแพลตฟอร์มไม่พร้อมใช้งาน", "The Platform console needs another try.": "โหลดคอนโซลแพลตฟอร์มไม่สำเร็จ โปรดลองอีกครั้ง",
  "Do not assume an operational command completed. Try the page again or return to the console and verify current state before repeating it.": "อย่าถือว่าคำสั่งดำเนินงานสำเร็จแล้ว โปรดลองโหลดหน้าอีกครั้งหรือกลับไปที่คอนโซลเพื่อตรวจสถานะปัจจุบันก่อนทำรายการซ้ำ",
  "Return to Platform Master": "กลับไประบบจัดการแพลตฟอร์ม", "This Platform page does not exist.": "ไม่มีหน้าแพลตฟอร์มนี้",
  "The address is not part of the restricted Platform console. No tenant, routing, support, or release state has been changed.": "ที่อยู่นี้ไม่ได้อยู่ในคอนโซลแพลตฟอร์มแบบจำกัดสิทธิ์ และไม่มีการเปลี่ยนสถานะลูกค้า เส้นทาง การสนับสนุน หรือการเปิดใช้",
  "Action reason": "เหตุผลการดำเนินการ", "Activate pilot": "เปิดโครงการนำร่อง",
  "% availability ·": "% พร้อมใช้งาน ·", "ms P95": "มิลลิวินาที P95", "Operational attestations": "หลักฐานรับรองการปฏิบัติงาน",
  "Excluded": "ไม่นำมารวม", "reserved": "จองไว้", "settled ·": "ชำระบัญชีแล้ว ·", "Review": "ตรวจสอบ", "Verified": "ยืนยันแล้ว",
  "Accept invitation": "ตอบรับคำเชิญ", "Accept ownership": "รับสิทธิ์เจ้าของ", "Accepting...": "กำลังตอบรับ…", "Joining...": "กำลังเข้าร่วม…",
  "Accepting makes you the Tenant Master Admin for this workspace.": "เมื่อตอบรับแล้ว คุณจะเป็นผู้ดูแลหลักของเวิร์กสเปซนี้",
  "Sign in with the email address that received this invitation.": "เข้าสู่ระบบด้วยอีเมลที่ได้รับคำเชิญนี้",
  "Confirm to add this workspace to your existing DJAY Bot account.": "ยืนยันเพื่อเพิ่มเวิร์กสเปซนี้ในบัญชี DJAY Bot ที่มีอยู่",
  "This invitation link is missing its secure acceptance token.": "ลิงก์คำเชิญนี้ไม่มีโทเคนตอบรับที่ปลอดภัย",
  "Sign in with the invited account to continue.": "เข้าสู่ระบบด้วยบัญชีที่ได้รับเชิญเพื่อดำเนินการต่อ",
  "Confirm email": "ยืนยันอีเมล", "Confirming...": "กำลังยืนยัน…", "Confirm this email to create the business workspace and its Tenant Master Admin account.": "ยืนยันอีเมลนี้เพื่อสร้างเวิร์กสเปซธุรกิจและบัญชีผู้ดูแลหลัก",
  "Request a new verification link below to continue creating the business workspace.": "ขอลิงก์ยืนยันใหม่ด้านล่างเพื่อสร้างเวิร์กสเปซธุรกิจต่อ",
  "The verification service could not be reached. Try this link again or request a new one.": "ติดต่อบริการยืนยันอีเมลไม่ได้ โปรดลองเปิดลิงก์นี้อีกครั้งหรือขอลิงก์ใหม่",
  "This link is invalid or expired.": "ลิงก์นี้ไม่ถูกต้องหรือหมดอายุแล้ว", "Send new link": "ส่งลิงก์ใหม่", "Sending...": "กำลังส่ง…",
  "Send recovery email": "ส่งอีเมลกู้คืนบัญชี", "This recovery link is invalid or expired.": "ลิงก์กู้คืนบัญชีไม่ถูกต้องหรือหมดอายุแล้ว",
  "Update password": "อัปเดตรหัสผ่าน", "Updating...": "กำลังอัปเดต…", "Sign in to your workspace": "เข้าสู่เวิร์กสเปซ",
  "Verify your identity": "ยืนยันตัวตน", "Verify": "ยืนยัน", "Verifying...": "กำลังยืนยัน…", "Signing in...": "กำลังเข้าสู่ระบบ…",
  "Create your account": "สร้างบัญชี", "Creating...": "กำลังสร้าง…", "Creating…": "กำลังสร้าง…", "Check your email": "ตรวจอีเมล",
  "Checking": "กำลังตรวจสอบ", "Checking current systems…": "กำลังตรวจสอบระบบปัจจุบัน…", "No current evidence": "ยังไม่มีหลักฐานปัจจุบัน",
  "Account created": "สร้างบัญชีแล้ว", "Action needed": "ต้องดำเนินการ", "Complete": "เสร็จสิ้น", "Continue setup": "ตั้งค่าต่อ",
  "Checking evidence…": "กำลังตรวจสอบหลักฐาน…", "Refresh checklist": "รีเฟรชรายการตรวจสอบ", "Setup in progress": "กำลังตั้งค่า", "Live operations": "การใช้งานจริง",
  "No products are configured yet": "ยังไม่ได้ตั้งค่าผลิตภัณฑ์", "Business knowledge": "ความรู้ของธุรกิจ", "Contact for price": "สอบถามราคา",
  "Workspace policy": "นโยบายเวิร์กสเปซ", "Save retention": "บันทึกระยะเวลาเก็บข้อมูล", "Saving...": "กำลังบันทึก…", "Saving…": "กำลังบันทึก…",
  "Choose a contact or export the entire workspace.": "เลือกข้อมูลติดต่อหนึ่งรายการ หรือส่งออกทั้งเวิร์กสเปซ",
  "Entire workspace export": "ส่งออกทั้งเวิร์กสเปซ", "Entire workspace": "ทั้งเวิร์กสเปซ", "Requesting...": "กำลังส่งคำขอ…",
  "Erasure always requires one specific contact and cannot target the entire workspace.": "การลบข้อมูลต้องเลือกข้อมูลติดต่อหนึ่งรายการเสมอ และไม่สามารถลบทั้งเวิร์กสเปซได้",
  "Select a contact to erase": "เลือกข้อมูลติดต่อที่จะลบ", "No active identity": "ไม่มีข้อมูลระบุตัวตนที่ใช้งานอยู่", "Save profile": "บันทึกโปรไฟล์",
  "No conversations": "ยังไม่มีการสนทนา", "No matches": "ไม่พบรายการ", "Product conversations will appear here.": "การสนทนาเกี่ยวกับผลิตภัณฑ์จะแสดงที่นี่",
  "Try another name, phone, or email.": "ลองค้นหาด้วยชื่อ โทรศัพท์ หรืออีเมลอื่น", "Conversation started": "เริ่มสนทนาเมื่อ", "· legal hold": "· ระงับการลบตามข้อกำหนด",
  "The durable call summary will appear after the first completed turn.": "สรุปสายแบบถาวรจะแสดงหลังจบช่วงสนทนาแรก", "Not requested": "ยังไม่ได้ขอ",
  "This conversation is currently automated.": "ขณะนี้ระบบอัตโนมัติกำลังดูแลการสนทนานี้", "Take over before replying.": "รับช่วงการสนทนาก่อนตอบกลับ", "Send reply": "ส่งข้อความตอบกลับ",
  "AI Chat Bot": "บอตแชต AI", "Your team": "ทีมของคุณ", "Loading": "กำลังโหลด", "No origin": "ยังไม่มีต้นทาง", "· published": "· เผยแพร่แล้ว",
  "· entry": "· จุดเริ่มต้น", "An administrator can create one.": "ผู้ดูแลสามารถสร้างได้", "Create the first bot.": "สร้างบอตตัวแรก",
  "Draft only": "เฉพาะฉบับร่าง", "Published": "เผยแพร่แล้ว", "Derived": "ได้จากการตั้งค่า", "Configuration dependency": "การตั้งค่าที่ต้องใช้ร่วมกัน",
  "No text captured": "ยังไม่มีข้อความที่บันทึก", "and FlowBot Premium where applicable": "และ FlowBot Premium ในกรณีที่เกี่ยวข้อง",
  "Facebook Page ID": "รหัสเพจ Facebook", "LINE account ID": "รหัสบัญชี LINE",
  "Recipients unavailable": "ข้อมูลผู้รับไม่พร้อม", "no actions": "ไม่มีการดำเนินการ", "Unavailable": "ไม่พร้อมใช้งาน", "Web runtime": "ระบบเว็บรันไทม์",
  "Action required": "ต้องดำเนินการ", "Ready on approved origin": "พร้อมใช้งานบนต้นทางที่อนุมัติ", "Publish required": "ต้องเผยแพร่ก่อน",
  "Available": "พร้อมใช้งาน", "Not included": "ไม่รวมในแผน", "Enabled": "เปิดใช้งานแล้ว", "Pending internal activation": "รอเปิดใช้งานภายใน",
  "Core analytics": "ข้อมูลวิเคราะห์หลัก", "Advanced analytics": "ข้อมูลวิเคราะห์ขั้นสูง", "Advanced": "ขั้นสูง",
  "Analytics could not be loaded": "โหลดข้อมูลวิเคราะห์ไม่สำเร็จ", "Call records remain intact.": "ข้อมูลสายยังคงอยู่ครบถ้วน",
  "No analytics are available yet": "ยังไม่มีข้อมูลวิเคราะห์", "Completed calls will appear here.": "สายที่เสร็จสิ้นจะแสดงที่นี่",
  "Create deployment": "สร้างการติดตั้ง", "Disable deployment": "ปิดการติดตั้ง", "Enable deployment": "เปิดการติดตั้ง", "Voice Agent is not active for this workspace.": "Voice Agent ยังไม่เปิดใช้งานในเวิร์กสเปซนี้",
  "Voice Agent Basic": "Voice Agent Basic", "Voice Agent Advanced": "Voice Agent Advanced", "Replace authenticator": "เปลี่ยนแอปยืนยันตัวตน",
  "Set up authenticator": "ตั้งค่าแอปยืนยันตัวตน", "Active session": "เซสชันที่ใช้งานอยู่", "Current session": "เซสชันปัจจุบัน", "Not verified": "ยังไม่ยืนยัน",
  "Pilot metering": "การวัดการใช้งานโครงการนำร่อง", "Configured": "ตั้งค่าแล้ว", "Not enabled": "ยังไม่เปิดใช้งาน", "Not set": "ยังไม่ได้ตั้งค่า",
  "Renews automatically": "ต่ออายุอัตโนมัติ", "Cancellation scheduled": "กำหนดยกเลิกแล้ว", "Annual renewal": "ต่ออายุรายปี",
  "Keep subscription": "ใช้การสมัครต่อ", "Cancel at term end": "ยกเลิกเมื่อสิ้นสุดรอบ", "Email delivery configured": "ตั้งค่าการส่งอีเมลแล้ว",
  "Email delivery not configured": "ยังไม่ได้ตั้งค่าการส่งอีเมล", "Enter email to update": "กรอกอีเมลเพื่ออัปเดต", "Unlimited": "ไม่จำกัด",
  "Invoices and credit notes will appear after Stripe finalizes them.": "ใบแจ้งหนี้และใบลดหนี้จะแสดงหลัง Stripe ยืนยันรายการแล้ว",
  "Public charging remains disabled until the commercial release gates are approved.": "ระบบยังไม่เปิดเรียกเก็บเงินสาธารณะจนกว่าเกณฑ์อนุมัติการเปิดขายจะผ่านครบถ้วน",
  "Credit note": "ใบลดหนี้", "New": "ใหม่", "Read": "อ่านแล้ว", "· checkout opens when this SKU is sellable": "· เปิดหน้าชำระเงินเมื่อ SKU นี้พร้อมจำหน่าย",
  "Ready for reviewed release": "พร้อมเปิดใช้หลังผ่านการตรวจ", "Release blocked": "ยังไม่อนุญาตให้เปิดใช้", "Healthy": "ปกติ", "Blocked": "ถูกระงับ",
  "Approved bundle required": "ต้องใช้ชุดข้อมูลที่อนุมัติแล้ว", "Evidence required": "ต้องมีหลักฐาน", "Current": "ปัจจุบัน", "blocked": "ถูกระงับ",
  "AI operations": "การดำเนินงาน AI", "Support operations": "การดำเนินงานสนับสนุน", "Platform Owner": "เจ้าของแพลตฟอร์ม", "Platform Finance": "ฝ่ายการเงินแพลตฟอร์ม",
  "Approve deployment only through the reviewed release workflow after this gate is ready.": "อนุมัติการติดตั้งผ่านขั้นตอนเปิดใช้ที่ผ่านการตรวจเท่านั้น และทำได้หลังเกณฑ์นี้พร้อมแล้ว",
  "Keep on-call and support-runbook evidence current; escalate every blocking incident.": "ปรับหลักฐานเวรรับผิดชอบและคู่มือสนับสนุนให้เป็นปัจจุบัน และยกระดับเหตุขัดข้องทุกกรณีที่กีดขวางการเปิดใช้",
  "Resolve failing runtime objectives without exposing internal routing to customer surfaces.": "แก้เป้าหมายรันไทม์ที่ไม่ผ่านโดยไม่เปิดเผยเส้นทางภายในบนหน้าจอลูกค้า",
  "This technical gate does not authorize prices, invoices, tax, or payment collection.": "เกณฑ์ทางเทคนิคนี้ไม่ได้ให้อำนาจกำหนดราคา ออกใบแจ้งหนี้ จัดการภาษี หรือรับชำระเงิน",
  "Attention required": "ต้องตรวจสอบ", "Platform Owner review": "การตรวจโดยเจ้าของแพลตฟอร์ม",
  "Pause rollout expansion when a variance appears and use the documented idempotent recovery workflow.": "หยุดขยายการเปิดใช้เมื่อพบความคลาดเคลื่อน และใช้ขั้นตอนกู้คืนแบบไม่เกิดผลซ้ำตามเอกสาร",
  "No variance": "ไม่พบความคลาดเคลื่อน", "No difference": "ไม่พบความแตกต่าง", "review requested": "ส่งให้ตรวจแล้ว",
  "No unresolved evidence": "ไม่มีหลักฐานที่ยังค้างตรวจ", "Active policy": "นโยบายที่ใช้งานอยู่", "none": "ไม่มี",
  "Enable traffic": "เปิดทราฟฟิก", "Disable traffic": "ปิดทราฟฟิก", "Enable": "เปิด", "Disable": "ปิด", "enabled": "เปิดอยู่", "fail-closed": "ปิดกั้นเพื่อความปลอดภัย",
  "paused": "หยุดชั่วคราว", "true": "ใช่", "false": "ไม่",
  "Platform sign in": "เข้าสู่ระบบแพลตฟอร์ม", "Checking...": "กำลังตรวจสอบ…", "Continue": "ดำเนินการต่อ",
  "Sign in is temporarily unavailable. Try again.": "ระบบเข้าสู่ระบบไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้ง", "Email or password is incorrect.": "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
  "Signed in. Opening your workspace...": "เข้าสู่ระบบแล้ว กำลังเปิดเวิร์กสเปซ…", "Signed in. Choose a workspace to continue.": "เข้าสู่ระบบแล้ว เลือกเวิร์กสเปซเพื่อดำเนินการต่อ",
  "Sign in is unavailable.": "ระบบเข้าสู่ระบบไม่พร้อมใช้งาน", "Identity verification is temporarily unavailable. Try again.": "ระบบยืนยันตัวตนไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้ง",
  "The verification code is invalid or expired.": "รหัสยืนยันไม่ถูกต้องหรือหมดอายุแล้ว",
  "If a pending account matches that email, a new verification link has been sent.": "หากมีบัญชีที่รอยืนยันตรงกับอีเมลนี้ ระบบได้ส่งลิงก์ยืนยันใหม่แล้ว",
  "Verification email delivery is temporarily unavailable. Try again shortly.": "การส่งอีเมลยืนยันไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้งในภายหลัง",
  "Enter a valid work email and try again.": "กรอกอีเมลที่ใช้ทำงานให้ถูกต้องแล้วลองใหม่",
  "Password recovery is temporarily unavailable. Try again.": "ระบบกู้คืนรหัสผ่านไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้ง",
  "This email already has an account. Continue to the secure sign-in journey to accept it.": "อีเมลนี้มีบัญชีอยู่แล้ว โปรดเข้าสู่ระบบอย่างปลอดภัยเพื่อตอบรับคำเชิญ",
  "Your team access is ready. Sign in to continue.": "สิทธิ์เข้าถึงทีมพร้อมแล้ว โปรดเข้าสู่ระบบเพื่อดำเนินการต่อ",
  "Invitation accepted. Sign in again to start a session with your updated workspace access.": "ตอบรับคำเชิญแล้ว โปรดเข้าสู่ระบบอีกครั้งเพื่อเริ่มเซสชันด้วยสิทธิ์เวิร์กสเปซล่าสุด",
  "Your sign-in expired before the invitation was accepted. Sign in again to continue.": "เซสชันเข้าสู่ระบบหมดอายุก่อนตอบรับคำเชิญ โปรดเข้าสู่ระบบอีกครั้ง",
  "Ownership transferred. Sign in again to start a new secure session.": "โอนสิทธิ์เจ้าของแล้ว โปรดเข้าสู่ระบบอีกครั้งเพื่อเริ่มเซสชันใหม่อย่างปลอดภัย",
  "Contact name must be 1–200 characters after removing leading and trailing spaces.": "ชื่อต้องมี 1–200 ตัวอักษรหลังตัดช่องว่างหน้าและท้าย",
  "Enter an email address or phone number.": "กรอกอีเมลหรือหมายเลขโทรศัพท์", "Phone number must be 7–32 characters after removing leading and trailing spaces.": "หมายเลขโทรศัพท์ต้องมี 7–32 ตัวอักษรหลังตัดช่องว่างหน้าและท้าย",
  "Deployment name must be 2–160 characters.": "ชื่อการติดตั้งต้องมี 2–160 ตัวอักษร", "Public agent name must be 2–100 characters.": "ชื่อเอเจนต์ที่แสดงต่อลูกค้าต้องมี 2–100 ตัวอักษร",
  "Business name must be 2–200 characters.": "ชื่อธุรกิจต้องมี 2–200 ตัวอักษร", "Each greeting must be 1–500 characters.": "คำทักทายแต่ละภาษาต้องมี 1–500 ตัวอักษร",
  "Each automated-agent disclosure must be 8–500 characters.": "ข้อความแจ้งว่าเป็นระบบอัตโนมัติแต่ละภาษาต้องมี 8–500 ตัวอักษร",
  "Enter 1–20 exact HTTPS origins without paths, queries, or fragments. Local HTTP is accepted only for localhost development.": "กรอกต้นทาง HTTPS ที่ตรงกัน 1–20 รายการ โดยไม่มี path, query หรือ fragment อนุญาต HTTP เฉพาะ localhost สำหรับการพัฒนา",
  "Maximum call seconds must be a whole number from 30 to 14,400.": "ระยะเวลาสายสูงสุดต้องเป็นจำนวนเต็มตั้งแต่ 30 ถึง 14,400 วินาที",
  "Reconnect window seconds must be a whole number from 0 to 300.": "ช่วงเวลาสำหรับเชื่อมต่อใหม่ต้องเป็นจำนวนเต็มตั้งแต่ 0 ถึง 300 วินาที",
  "Enter an exact HTTPS origin without a path, query, or fragment. Local HTTP is accepted only for localhost development.": "กรอกต้นทาง HTTPS ที่ตรงกันโดยไม่มี path, query หรือ fragment อนุญาต HTTP เฉพาะ localhost สำหรับการพัฒนา",
  "Schedule key must start with a lowercase letter and use only lowercase letters, numbers, underscores, or hyphens (maximum 100 characters).": "รหัสตารางต้องขึ้นต้นด้วยอักษรอังกฤษตัวพิมพ์เล็ก และใช้ได้เฉพาะตัวพิมพ์เล็ก ตัวเลข ขีดล่าง หรือขีดกลาง (ไม่เกิน 100 ตัวอักษร)",
  "Schedule name must be 2–160 characters.": "ชื่อตารางต้องมี 2–160 ตัวอักษร", "Enter a supported IANA timezone, such as Asia/Bangkok.": "กรอกเขตเวลา IANA ที่รองรับ เช่น Asia/Bangkok",
  "Team key must start with a lowercase letter and use only lowercase letters, numbers, underscores, or hyphens (maximum 100 characters).": "รหัสทีมต้องขึ้นต้นด้วยอักษรอังกฤษตัวพิมพ์เล็ก และใช้ได้เฉพาะตัวพิมพ์เล็ก ตัวเลข ขีดล่าง หรือขีดกลาง (ไม่เกิน 100 ตัวอักษร)",
  "Team name must be 2–160 characters.": "ชื่อทีมต้องมี 2–160 ตัวอักษร", "Select 1–100 active team members.": "เลือกสมาชิกทีมที่ใช้งานอยู่ 1–100 คน",
  "Bot created.": "สร้างบอตแล้ว", "Draft saved.": "บันทึกฉบับร่างแล้ว", "Definition must be valid JSON. Repair it in the open Advanced JSON editor.": "ข้อมูลต้องเป็น JSON ที่ถูกต้อง โปรดแก้ไขในตัวแก้ไข JSON ขั้นสูงที่เปิดอยู่",
  "Deployment could not be created.": "สร้างการติดตั้งไม่สำเร็จ", "Deployment key created. It is shown once.": "สร้างกุญแจการติดตั้งแล้ว ระบบจะแสดงเพียงครั้งเดียว",
  "Business profile saved. Return to Overview to continue the launch checklist.": "บันทึกโปรไฟล์ธุรกิจแล้ว กลับไปหน้าภาพรวมเพื่อดำเนินการตามรายการก่อนเปิดใช้ต่อ",
  "Recovery is unavailable. Try again shortly.": "ระบบกู้คืนบัญชีไม่พร้อมใช้งาน โปรดลองอีกครั้งในภายหลัง",
  "Select the product contract that will receive this add-on.": "เลือกสัญญาผลิตภัณฑ์ที่จะรับส่วนเสริมนี้",
  "The requested knowledge change could not be completed.": "ดำเนินการเปลี่ยนแปลงคลังความรู้ไม่สำเร็จ", "File uploaded. Malware scanning and extraction are queued.": "อัปโหลดไฟล์แล้ว ระบบจัดคิวตรวจมัลแวร์และแยกเนื้อหา",
  "The file could not be uploaded.": "อัปโหลดไฟล์ไม่สำเร็จ", "Contact could not be created.": "สร้างข้อมูลติดต่อไม่สำเร็จ", "Contact created.": "สร้างข้อมูลติดต่อแล้ว",
  "Customer metadata could not be saved. Check attribute keys and typed values.": "บันทึกข้อมูลเพิ่มเติมของลูกค้าไม่สำเร็จ โปรดตรวจรหัสฟิลด์และค่าตามประเภทข้อมูล",
  "Customer metadata saved.": "บันทึกข้อมูลเพิ่มเติมของลูกค้าแล้ว", "Evidence refreshed from the server.": "รีเฟรชหลักฐานจากเซิร์ฟเวอร์แล้ว", "Evidence could not be refreshed.": "รีเฟรชหลักฐานไม่สำเร็จ",
  "Business profile saved. Default weekday hours (09:00–17:00) were applied when Flow Bot schedules are available.": "บันทึกโปรไฟล์ธุรกิจแล้ว และใช้เวลาทำการเริ่มต้นวันจันทร์–ศุกร์ 09:00–17:00 เมื่อระบบตาราง FlowBot พร้อมใช้งาน",
  "Bot could not be created. Confirm Flow Bot access is active.": "สร้างบอตไม่สำเร็จ โปรดตรวจว่าสิทธิ์ FlowBot เปิดใช้งานแล้ว", "Bot created. Apply a template and publish next.": "สร้างบอตแล้ว ขั้นต่อไปให้ใช้เทมเพลตและเผยแพร่",
  "Deployment key created. It is shown once — copy the snippet before leaving this step.": "สร้างกุญแจการติดตั้งแล้ว ระบบจะแสดงเพียงครั้งเดียว โปรดคัดลอกโค้ดก่อนออกจากขั้นตอนนี้",
  "Lead could not be created.": "สร้างข้อมูลผู้สนใจไม่สำเร็จ", "Lead created.": "สร้างข้อมูลผู้สนใจแล้ว",
  "Draft saved. Active calls remain pinned to their original published version.": "บันทึกฉบับร่างแล้ว สายที่กำลังใช้งานจะยังยึดเวอร์ชันเดิมที่เผยแพร่ไว้",
  "Enter an exact HTTPS origin without a path, query, or fragment.": "กรอกต้นทาง HTTPS ที่ตรงกันโดยไม่มี path, query หรือ fragment",
  "Deployment created. Copy its key now; it will not be shown again.": "สร้างการติดตั้งแล้ว โปรดคัดลอกกุญแจตอนนี้ เพราะระบบจะไม่แสดงอีก",
  "Select the snippet and copy it manually.": "เลือกโค้ดแล้วคัดลอกด้วยตนเอง", "Install snippet copied.": "คัดลอกโค้ดติดตั้งแล้ว", "Copy was blocked. Select the snippet and copy it manually.": "เบราว์เซอร์ไม่อนุญาตให้คัดลอก โปรดเลือกโค้ดแล้วคัดลอกด้วยตนเอง",
  "Invitation queued for delivery.": "จัดคิวส่งคำเชิญแล้ว", "AI agent could not be created.": "สร้างเอเจนต์ AI ไม่สำเร็จ", "AI agent created.": "สร้างเอเจนต์ AI แล้ว",
  "Draft and knowledge pins saved.": "บันทึกฉบับร่างและความรู้ที่ตรึงไว้แล้ว", "Website deployment could not be created.": "สร้างการติดตั้งบนเว็บไซต์ไม่สำเร็จ",
  "Test mode is temporarily unavailable.": "โหมดทดสอบไม่พร้อมใช้งานชั่วคราว", "Preview generated. No action was executed and no customer usage was charged.": "สร้างตัวอย่างแล้ว โดยยังไม่มีการดำเนินการและไม่คิดการใช้งานของลูกค้า",
  "LINE connected. Copy the webhook URL now; its key is shown once.": "เชื่อมต่อ LINE แล้ว โปรดคัดลอก URL ของ webhook ตอนนี้ เพราะระบบจะแสดงกุญแจเพียงครั้งเดียว",
  "WhatsApp connected. Copy the callback URL now; its key is shown once.": "เชื่อมต่อ WhatsApp แล้ว โปรดคัดลอก URL callback ตอนนี้ เพราะระบบจะแสดงกุญแจเพียงครั้งเดียว",
  "Messenger connected. Copy the callback URL now; its key is shown once.": "เชื่อมต่อ Messenger แล้ว โปรดคัดลอก URL callback ตอนนี้ เพราะระบบจะแสดงกุญแจเพียงครั้งเดียว",
  "Fix the Advanced JSON before selecting a recipient.": "แก้ไข JSON ขั้นสูงให้ถูกต้องก่อนเลือกผู้รับ", "Sign out could not be confirmed. Your current session remains open.": "ยืนยันการออกจากระบบไม่สำเร็จ เซสชันปัจจุบันยังคงเปิดอยู่",
  "Support access request could not be created.": "สร้างคำขอสิทธิ์เข้าถึงเพื่อให้การสนับสนุนไม่สำเร็จ",
  "All systems operational": "ทุกระบบทำงานตามปกติ",
};

const ambiguousCustomerValues = new Set(["Contact", "No", "Yes", "Unknown", "unknown"]);
const englishUi = new Map<string, string>();
for (const [english, thai] of Object.entries(thaiUi)) {
  if (!englishUi.has(thai)) englishUi.set(thai, english);
}
// Approved Thai-first variants used by newer public surfaces. Keep these explicit so
// customer-authored Thai prose is never translated heuristically.
englishUi.set("สร้างพื้นที่ทำงาน", "Create workspace");
englishUi.set("ลองอีกครั้ง", "Try again");
englishUi.set("ข้อกำหนดบริการ", "Service Terms");

export function translateThaiUi(value: string): string {
  const trimmed = value.trim();
  if (ambiguousCustomerValues.has(trimmed)) return value;
  const translated = thaiUi[trimmed];
  if (!translated) return value;
  const start = value.indexOf(trimmed);
  return `${value.slice(0, start)}${translated}${value.slice(start + trimmed.length)}`;
}

/** Reverse an exact translated UI string for the English presentation boundary.
 * Inputs, textareas, and explicitly unlocalized customer content are excluded by the
 * browser boundary before this function is called. */
export function translateEnglishUi(value: string): string {
  const trimmed = value.trim();
  const translated = englishUi.get(trimmed);
  if (!translated) return value;
  const start = value.indexOf(trimmed);
  return `${value.slice(0, start)}${translated}${value.slice(start + trimmed.length)}`;
}
