"use client";

import { useLayoutEffect, useRef, useState } from "react";

type Locale = "th" | "en";

const THAI: Record<string, string> = {
  ". Historical records remain linked by snapshot or ID.": " ข้อมูลย้อนหลังยังคงเชื่อมโยงด้วยสำเนาข้อมูลหรือรหัสรายการ",
  ". Narrow search or filters to find older conversations.": " ปรับคำค้นหาหรือตัวกรองให้แคบลงเพื่อค้นหาการสนทนาที่เก่ากว่า",
  ". Narrow search or filters to find older leads.": " ปรับคำค้นหาหรือตัวกรองให้แคบลงเพื่อค้นหาผู้สนใจที่เก่ากว่า",
  "1. Calendar profile": "1. โปรไฟล์ปฏิทิน",
  "2. Weekly availability": "2. เวลารับนัดรายสัปดาห์",
  "3. Block busy time": "3. ปิดช่วงเวลาที่ไม่ว่าง",
  "4. Create booking link": "4. สร้างลิงก์จอง",
  "2 hours": "2 ชั่วโมง",
  "Active AI booking": "การจองผ่าน AI ที่ใช้งานอยู่",
  "Add time rule": "เพิ่มกติกาเวลา",
  "Appointment action failed:": "ดำเนินการกับนัดหมายไม่สำเร็จ:",
  "Availability saved.": "บันทึกเวลารับนัดแล้ว",
  "Availability update failed:": "อัปเดตเวลารับนัดไม่สำเร็จ:",
  "Booking is currently": "ขณะนี้การจอง",
  "Booking is enabled but no active AI booking link is selected.": "เปิดใช้งานการจองแล้ว แต่ยังไม่ได้เลือกลิงก์จองที่ให้ AI ใช้",
  "Booking link action failed:": "ดำเนินการกับลิงก์จองไม่สำเร็จ:",
  "Booking links updated.": "อัปเดตลิงก์จองแล้ว",
  "Booking replacement...": "ลิงก์จองที่จะใช้แทน...",
  "Booking slug compatibility": "ความเข้ากันได้ของชื่อท้ายลิงก์จอง",
  "Booking slug:": "ชื่อท้ายลิงก์จอง:",
  "Calendar action failed:": "ดำเนินการกับปฏิทินไม่สำเร็จ:",
  "Calendar setup saved.": "บันทึกการตั้งค่าปฏิทินแล้ว",
  "Cancel future": "ยกเลิกรายการในอนาคต",
  "Compatibility slug": "ชื่อท้ายลิงก์เพื่อความเข้ากันได้",
  "Conversations with usable contact details become leads automatically. Admin edits to lead status and notes are kept separate from the voice model.": "การสนทนาที่มีช่องทางติดต่อที่ใช้งานได้จะกลายเป็นข้อมูลผู้สนใจโดยอัตโนมัติ การแก้ไขสถานะและบันทึกโดยผู้ดูแลจะแยกจากข้อมูลของโมเดลเสียง",
  "Delete link": "ลบลิงก์",
  "Disable booking if this admin is active booking admin": "ปิดการจองหากผู้ดูแลรายนี้เป็นผู้รับนัดที่ใช้งานอยู่",
  "Editing setup for": "กำลังแก้ไขการตั้งค่าสำหรับ",
  "Manage bookable hours and blocked time for": "จัดการเวลารับนัดและช่วงไม่ว่างสำหรับ",
  "Meeting location/link": "สถานที่หรือลิงก์นัดหมาย",
  "Meeting title": "ชื่อนัดหมาย",
  "No active admin is available for calendar setup.": "ไม่มีผู้ดูแลที่เปิดใช้งานสำหรับตั้งค่าปฏิทิน",
  "Open appointment": "เปิดนัดหมาย",
  "Reassign future": "มอบหมายรายการในอนาคตใหม่",
  "Set as AI booking link": "กำหนดเป็นลิงก์จองสำหรับ AI",
  "Setup update failed:": "อัปเดตการตั้งค่าไม่สำเร็จ:",
  "Showing the latest": "กำลังแสดงรายการล่าสุด",
  "Step": "ขั้นตอน",
  "Team action failed:": "ดำเนินการกับทีมไม่สำเร็จ:",
  "The voice agent sends appointment-ready leads to one selected booking link.": "ผู้ช่วยเสียงจะส่งผู้สนใจที่พร้อมนัดหมายไปยังลิงก์จองที่เลือกไว้หนึ่งรายการ",
  "This calendar is not fully ready. Complete profile, weekly hours, and at least one booking link in setup.": "ปฏิทินยังไม่พร้อมใช้งาน โปรดกรอกโปรไฟล์ เวลารายสัปดาห์ และสร้างลิงก์จองอย่างน้อยหนึ่งรายการ",
  "This is for text analysis after the call. It does not affect the live voice model.": "ส่วนนี้ใช้วิเคราะห์ข้อความหลังจบการสนทนา และไม่กระทบโมเดลเสียงที่กำลังสนทนา",
  "Unassign future": "ยกเลิกการมอบหมายรายการในอนาคต",
  "Version": "เวอร์ชัน",
  "Voice": "เสียง",
  "days · Buffer": "วัน · เวลาพัก",
  "has no weekly availability configured.": "ยังไม่ได้กำหนดเวลารับนัดรายสัปดาห์",
  "min": "นาที",
  "min ·": "นาที ·",
  "min · Upcoming": "นาที · กำลังจะมาถึง",
  "min · Window": "นาที · ช่วงเปิดจอง",
  "AI booking link selected": "เลือกลิงก์จองสำหรับ AI แล้ว",
  "Booking is disabled or no AI booking link is selected.": "ปิดใช้งานการจองหรือยังไม่ได้เลือกลิงก์จองสำหรับ AI",
  "Busy": "ไม่ว่าง",
  "Cancel this appointment?": "ต้องการยกเลิกนัดหมายนี้หรือไม่",
  "Chat": "แชต",
  "Connected": "เชื่อมต่อแล้ว",
  "Create a booking link to preview slots.": "สร้างลิงก์จองเพื่อดูตัวอย่างเวลาที่จองได้",
  "Deactivate this admin? They will no longer be able to log in.": "ต้องการปิดใช้งานผู้ดูแลรายนี้หรือไม่ ผู้ดูแลรายนี้จะเข้าสู่ระบบไม่ได้อีก",
  "Delete selected conversations? This hides them from normal admin lists.": "ต้องการลบการสนทนาที่เลือกหรือไม่ รายการจะไม่แสดงในหน้าผู้ดูแลตามปกติ",
  "Delete this admin? Historical records remain, but login will be revoked.": "ต้องการลบผู้ดูแลรายนี้หรือไม่ ข้อมูลย้อนหลังจะยังอยู่ แต่บัญชีจะเข้าสู่ระบบไม่ได้",
  "Delete this availability override?": "ต้องการลบข้อยกเว้นเวลานี้หรือไม่",
  "Delete this booking link? Historical appointments stay linked.": "ต้องการลบลิงก์จองนี้หรือไม่ นัดหมายย้อนหลังจะยังเชื่อมโยงอยู่",
  "Delete this conversation? This hides it from normal admin lists.": "ต้องการลบการสนทนานี้หรือไม่ รายการจะไม่แสดงในหน้าผู้ดูแลตามปกติ",
  "Disabled": "ปิดใช้งาน",
  "Enabled": "เปิดใช้งาน",
  "Follow up": "ติดตาม",
  "Hide deleted": "ซ่อนรายการที่ลบ",
  "List": "รายการ",
  "Manage all team appointments.": "จัดการนัดหมายของทีมทั้งหมด",
  "Manage your assigned appointments.": "จัดการนัดหมายที่มอบหมายให้คุณ",
  "Manual or imported lead": "ข้อมูลผู้สนใจที่เพิ่มเองหรือนำเข้า",
  "More": "เพิ่มเติม",
  "Needs setup": "ต้องตั้งค่าเพิ่มเติม",
  "Never": "ไม่เคย",
  "No booking link selected for the voice agent.": "ยังไม่ได้เลือกลิงก์จองสำหรับผู้ช่วยเสียง",
  "No company captured": "ไม่มีข้อมูลบริษัท",
  "No conversations yet": "ยังไม่มีการสนทนา",
  "No next action": "ไม่มีขั้นตอนถัดไป",
  "No next action captured": "ไม่มีข้อมูลขั้นตอนถัดไป",
  "No problem summary yet.": "ยังไม่มีสรุปปัญหา",
  "No summary yet.": "ยังไม่มีสรุป",
  "None": "ไม่มี",
  "Not captured": "ไม่มีข้อมูล",
  "Not configured": "ยังไม่ได้ตั้งค่า",
  "Password update failed. Check the current password and confirmation.": "อัปเดตรหัสผ่านไม่สำเร็จ โปรดตรวจรหัสผ่านปัจจุบันและการยืนยันรหัสผ่าน",
  "Password updated.": "อัปเดตรหัสผ่านแล้ว",
  "Ready": "พร้อมใช้งาน",
  "Reject this appointment?": "ต้องการปฏิเสธนัดหมายนี้หรือไม่",
  "Review": "ตรวจสอบ",
  "Selected link": "ลิงก์ที่เลือก",
  "The active booking admin": "ผู้ดูแลที่รับนัดหมายอยู่",
  "Unnamed": "ไม่มีชื่อ",
  "Unnamed lead": "ผู้สนใจที่ไม่มีชื่อ",
  "Unstar": "ยกเลิกการติดดาว",
  "View deleted": "ดูรายการที่ลบ",
  "Visitor": "ผู้เข้าชม",
  "no model": "ไม่มีโมเดล",
  "not analysed": "ยังไม่ได้วิเคราะห์",
  "text chat": "แชตข้อความ",
  "unknown page": "ไม่ทราบหน้าเว็บ",
  "· AI active": "· AI ใช้งานอยู่",
  "Pending follow up": "รอติดตาม",
  "Appointment set": "นัดหมายแล้ว",
  "Follow up later": "ติดตามภายหลัง",
  "Deal closed": "ปิดการขายแล้ว",
  "No deal": "ไม่ปิดการขาย",
  "Pending": "รอดำเนินการ",
  "Confirmed": "ยืนยันแล้ว",
  "Rejected": "ปฏิเสธแล้ว",
  "Cancelled": "ยกเลิกแล้ว",
  "Completed": "เสร็จสิ้น",
  "Appointment": "นัดหมาย",
  "Failed": "ล้มเหลว",
  "pending follow up": "รอติดตาม",
  "appointment set": "นัดหมายแล้ว",
  "follow up later": "ติดตามภายหลัง",
  "deal closed": "ปิดการขายแล้ว",
  "no deal": "ไม่ปิดการขาย",
  "pending confirmation": "รอยืนยัน",
  "confirmed": "ยืนยันแล้ว",
  "rejected": "ปฏิเสธแล้ว",
  "cancelled": "ยกเลิกแล้ว",
  "completed": "เสร็จสิ้น",
  "no show": "ไม่มาตามนัด",
  "pending": "รอดำเนินการ",
  "failed": "ล้มเหลว",
  "active": "ใช้งานอยู่",
  "inactive": "ปิดใช้งาน",
  "unknown": "ยังไม่ทราบ",
  "Appts today": "นัดหมายวันนี้",
  "Avg duration": "ระยะเวลาเฉลี่ย",
  "Capture rate": "อัตราเก็บข้อมูลผู้สนใจ",
  "High interest": "สนใจสูง",
  "Leads captured": "ผู้สนใจที่เก็บข้อมูลได้",
  "Text appts": "นัดหมายจากแชต",
  "Text leads": "ผู้สนใจจากแชต",
  "Voice appts": "นัดหมายจากเสียง",
  "Voice leads": "ผู้สนใจจากเสียง",
  "pending_confirmation": "รอยืนยัน",
  "pending_follow_up": "รอติดตาม",
  "Sales Agent Admin": "ระบบจัดการผู้ช่วยฝ่ายขาย",
  "Voice Sales Agent": "ผู้ช่วยฝ่ายขายด้วยเสียง",
  "Overview": "ภาพรวม",
  "Inbox": "กล่องข้อความ",
  "Leads": "ผู้สนใจ",
  "Calendar": "ปฏิทิน",
  "Channels": "ช่องทาง",
  "Team": "ทีมงาน",
  "Settings": "การตั้งค่า",
  "Master admin": "ผู้ดูแลระบบหลัก",
  "Admin": "ผู้ดูแลระบบ",
  "Sign out": "ออกจากระบบ",
  "Sign in": "เข้าสู่ระบบ",
  "Username": "ชื่อผู้ใช้",
  "Password": "รหัสผ่าน",
  "Voice agent live": "ผู้ช่วยเสียงพร้อมใช้งาน",
  "Voice agent disabled": "ปิดใช้งานผู้ช่วยเสียง",
  "Booking enabled": "เปิดใช้งานการจอง",
  "Booking disabled": "ปิดใช้งานการจอง",
  "Too many attempts. Try again shortly.": "ลองเข้าสู่ระบบหลายครั้งเกินไป กรุณารอสักครู่แล้วลองใหม่",
  "Invalid admin credentials.": "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
  "Action queue": "รายการที่ต้องดำเนินการ",
  "Daily sales command center for calls, leads, appointments, and follow-up work.": "ศูนย์รวมงานขายประจำวัน ทั้งการสนทนา ข้อมูลผู้สนใจ นัดหมาย และงานติดตาม",
  "Pending follow-up": "รอติดตาม",
  "Leads waiting for admin action": "ผู้สนใจที่รอผู้ดูแลดำเนินการ",
  "Pending confirmations": "รอยืนยัน",
  "Appointments that need confirm or reject": "นัดหมายที่ต้องยืนยันหรือปฏิเสธ",
  "Analysis review": "ตรวจสอบผลวิเคราะห์",
  "Open failed or pending post-call analysis": "เปิดผลวิเคราะห์หลังการสนทนาที่ล้มเหลวหรือยังไม่เสร็จ",
  "Open Inbox": "เปิดกล่องข้อความ",
  "Booking calendar": "ปฏิทินนัดหมาย",
  "Choose a link": "เลือกลิงก์",
  "Set hours": "กำหนดเวลาทำการ",
  "Exports and operations": "ส่งออกข้อมูลและจัดการระบบ",
  "Export conversations": "ส่งออกการสนทนา",
  "Export leads": "ส่งออกข้อมูลผู้สนใจ",
  "Export appointments": "ส่งออกนัดหมาย",
  "Needs follow-up": "รายการที่ต้องติดตาม",
  "Recent conversations": "การสนทนาล่าสุด",
  "No pending follow-up leads.": "ไม่มีผู้สนใจที่รอติดตาม",
  "No pending follow-up or appointment confirmations.": "ไม่มีผู้สนใจหรือนัดหมายที่รอดำเนินการ",
  "No conversations yet.": "ยังไม่มีการสนทนา",
  "Lead": "ผู้สนใจ",
  "No lead": "ไม่มีข้อมูลผู้สนใจ",
  "Leads:": "ผู้สนใจ:",
  "conversations": "การสนทนา",
  "Check": "ตรวจสอบ",
  "Open": "เปิด",
  "Active": "ใช้งานอยู่",
  "Inactive": "ปิดใช้งาน",
  "Future": "ยังไม่เปิดใช้งาน",
  "Unknown": "ยังไม่ทราบ",
  "High": "สูง",
  "Medium": "ปานกลาง",
  "Low": "ต่ำ",
  "high interest": "สนใจสูง",
  "medium interest": "สนใจปานกลาง",
  "low interest": "สนใจต่ำ",
  "unknown interest": "ยังไม่ทราบระดับความสนใจ",
  "Connected channels": "ช่องทางที่เชื่อมต่อแล้ว",
  "Future channels": "ช่องทางในอนาคต",
  "Future channel roadmap": "แผนเพิ่มช่องทางในอนาคต",
  "Website Agent Widget": "วิดเจ็ตผู้ช่วยบนเว็บไซต์",
  "Production voice and text agent embedded on the website.": "ผู้ช่วยเสียงและแชตที่ติดตั้งใช้งานจริงบนเว็บไซต์",
  "Live voice and text conversations from the embedded DJAI website agent.": "การสนทนาด้วยเสียงและข้อความจากผู้ช่วย DJAI ที่ฝังอยู่บนเว็บไซต์",
  "Manage connected conversation channels. This version enables the website voicebot and text chatbot.": "จัดการช่องทางสนทนาที่เชื่อมต่อ เวอร์ชันนี้เปิดใช้งานผู้ช่วยเสียงและแชตบอตบนเว็บไซต์",
  "These cards are placeholders only. They do not represent working integrations in this build.": "รายการเหล่านี้แสดงแผนงานเท่านั้น ยังไม่ใช่การเชื่อมต่อที่ใช้งานได้ในเวอร์ชันนี้",
  "Not connected in this version.": "ยังไม่เชื่อมต่อในเวอร์ชันนี้",
  ". Not connected in this version.": " ยังไม่เชื่อมต่อในเวอร์ชันนี้",
  "Provider": "ผู้ให้บริการ",
  "Voice model": "โมเดลเสียง",
  "Text model": "โมเดลข้อความ",
  "Text chatbot": "แชตบอตข้อความ",
  "Booking CTA": "ปุ่มนัดหมาย",
  "Workspace": "พื้นที่ทำงาน",
  "Voice calls": "การสนทนาด้วยเสียง",
  "Text chats": "การสนทนาด้วยข้อความ",
  "Conversations": "การสนทนา",
  "View inbox channels": "ดูช่องทางในกล่องข้อความ",
  "Consolidated channel workspace for the website voicebot and text chatbot.": "พื้นที่รวมการสนทนาจากผู้ช่วยเสียงและแชตบอตบนเว็บไซต์",
  "Sales pipeline for captured contacts, status, notes, and follow-up actions.": "ขั้นตอนงานขายสำหรับจัดการข้อมูลติดต่อ สถานะ บันทึก และการติดตาม",
  "Search leads": "ค้นหาผู้สนใจ",
  "Search": "ค้นหา",
  "Lead pipeline ·": "ขั้นตอนงานขาย ·",
  "Lead detail": "รายละเอียดผู้สนใจ",
  "Select a lead from the list.": "เลือกผู้สนใจจากรายการ",
  "No leads in this view.": "ไม่มีผู้สนใจในมุมมองนี้",
  "Open conversation": "เปิดการสนทนา",
  "Updated": "อัปเดตเมื่อ",
  "Client name": "ชื่อลูกค้า",
  "Company": "บริษัท",
  "Phone": "โทรศัพท์",
  "Email": "อีเมล",
  "Other contact": "ช่องทางติดต่ออื่น",
  "Business type": "ประเภทธุรกิจ",
  "Business goal": "เป้าหมายธุรกิจ",
  "Main problem": "ปัญหาหลัก",
  "Recommended service": "บริการที่แนะนำ",
  "Preferred contact": "ช่องทางที่สะดวก",
  "Meeting day": "วันที่สะดวกนัดหมาย",
  "Meeting time": "เวลาที่สะดวกนัดหมาย",
  "Lead status": "สถานะผู้สนใจ",
  "Admin notes": "บันทึกภายใน",
  "Assigned to": "มอบหมายให้",
  "Unassigned": "ยังไม่ได้มอบหมาย",
  "Save lead": "บันทึกข้อมูลผู้สนใจ",
  "Delete selected": "ลบรายการที่เลือก",
  "Updated:": "อัปเดตเมื่อ:",
  "Created:": "สร้างเมื่อ:",
  "Source:": "ช่องทางต้นทาง:",
  "Lead status:": "สถานะผู้สนใจ:",
  "Customers can only book inside these hours unless you add an extra-available override.": "ลูกค้าจองได้เฉพาะช่วงเวลาเหล่านี้ เว้นแต่เพิ่มช่วงเวลาพิเศษ",
  "Customers": "ลูกค้า",
  "Contact profiles": "ข้อมูลติดต่อ",
  "Lightweight contact profiles derived from captured leads. Database profile merging is not automatic in this version.": "ข้อมูลติดต่อสรุปจากผู้สนใจที่ระบบเก็บได้ เวอร์ชันนี้ยังไม่รวมข้อมูลซ้ำในฐานข้อมูลโดยอัตโนมัติ",
  "No captured customer/contact profiles yet.": "ยังไม่มีข้อมูลลูกค้าหรือช่องทางติดต่อ",
  "Calendar setup is incomplete. You need an active profile, weekly hours, booking link, and one AI active booking link.": "การตั้งค่าปฏิทินยังไม่ครบ ต้องมีโปรไฟล์ที่ใช้งาน เวลาทำการรายสัปดาห์ ลิงก์จอง และลิงก์หนึ่งรายการที่เปิดให้ AI ใช้",
  "Open setup": "เปิดหน้าตั้งค่า",
  "Review appointments, confirm requests, and manage blocked time from one weekly schedule.": "ตรวจสอบนัดหมาย ยืนยันคำขอ และจัดการช่วงเวลาที่ไม่ว่างจากตารางรายสัปดาห์",
  "Setup": "ตั้งค่า",
  "Availability": "เวลาที่เปิดรับนัด",
  "Booking links": "ลิงก์จอง",
  "Previous": "ก่อนหน้า",
  "Today": "วันนี้",
  "Next": "ถัดไป",
  "All admins": "ผู้ดูแลทั้งหมด",
  "Apply": "นำไปใช้",
  "Search customer or issue": "ค้นหาลูกค้าหรือหัวข้อ",
  "Blocked": "ไม่ว่าง",
  "Blocked ·": "ไม่ว่าง ·",
  "Appointment detail": "รายละเอียดนัดหมาย",
  "Confirm, reject, reschedule, reassign, or add notes.": "ยืนยัน ปฏิเสธ เปลี่ยนเวลา มอบหมายใหม่ หรือเพิ่มบันทึก",
  "Problem:": "ปัญหา:",
  "Service:": "บริการ:",
  "Client note:": "บันทึกจากลูกค้า:",
  "Confirm": "ยืนยัน",
  "Reject": "ปฏิเสธ",
  "Complete": "เสร็จสิ้น",
  "No-show": "ไม่มาตามนัด",
  "Reschedule": "เปลี่ยนเวลานัด",
  "Reassign": "มอบหมายใหม่",
  "Save notes": "บันทึกหมายเหตุ",
  "Internal appointment notes": "บันทึกนัดหมายสำหรับทีมงาน",
  "Open leads": "เปิดหน้าผู้สนใจ",
  "No appointment in this week. Use Booking links to share a public scheduler.": "สัปดาห์นี้ไม่มีนัดหมาย ใช้ลิงก์จองเพื่อแชร์หน้าจองให้ลูกค้า",
  "Set up calendar": "ตั้งค่าปฏิทิน",
  "Create the calendar profile, open appointment hours, and booking link before sending visitors to book.": "สร้างโปรไฟล์ปฏิทิน กำหนดเวลารับนัด และสร้างลิงก์จองก่อนส่งให้ผู้เข้าชม",
  "Setup checklist": "รายการตรวจสอบการตั้งค่า",
  "Switch": "เปลี่ยน",
  "Calendar profile": "โปรไฟล์ปฏิทิน",
  "Display name": "ชื่อที่แสดง",
  "Booking slug": "ชื่อท้ายลิงก์จอง",
  "Default timezone": "เขตเวลาเริ่มต้น",
  "Default meeting title": "ชื่อการนัดหมายเริ่มต้น",
  "Default meeting location/link": "สถานที่หรือลิงก์เริ่มต้น",
  "Default location/link": "สถานที่หรือลิงก์เริ่มต้น",
  "Default duration": "ระยะเวลาเริ่มต้น",
  "Save profile": "บันทึกโปรไฟล์",
  "Weekly availability": "เวลารับนัดรายสัปดาห์",
  "Weekly open hours": "เวลาทำการรายสัปดาห์",
  "Set your default open appointment hours. Leave a day empty if unavailable.": "กำหนดเวลารับนัดตามปกติ หากวันใดไม่เปิดรับนัดให้เว้นว่างไว้",
  "Save weekly hours": "บันทึกเวลารายสัปดาห์",
  "Block busy time": "ปิดช่วงเวลาที่ไม่ว่าง",
  "Optional. Add a busy period so customers cannot book it.": "เพิ่มช่วงเวลาที่ไม่ว่างเพื่อป้องกันไม่ให้ลูกค้าจอง (ไม่บังคับ)",
  "Add blocked time": "เพิ่มช่วงเวลาที่ไม่ว่าง",
  "Client visit, holiday, focus time...": "พบลูกค้า วันหยุด เวลาทำงานที่ต้องใช้สมาธิ...",
  "Create booking link": "สร้างลิงก์จอง",
  "Existing links": "ลิงก์ที่มีอยู่",
  "Active AI booking link": "ลิงก์จองที่ AI ใช้งานอยู่",
  "Create consultation links with duration and booking rules. Master admin chooses which one the AI voice agent uses.": "สร้างลิงก์นัดปรึกษาพร้อมระยะเวลาและกติกาการจอง ผู้ดูแลระบบหลักเป็นผู้เลือกลิงก์ที่ผู้ช่วยเสียง AI จะใช้",
  "Manage booking links": "จัดการลิงก์จอง",
  "Create link": "สร้างลิงก์",
  "Existing booking links": "ลิงก์จองที่มีอยู่",
  "AI active": "AI ใช้งานอยู่",
  "Calendar active": "ปฏิทินใช้งานอยู่",
  "Calendar inactive": "ปฏิทินปิดใช้งาน",
  "Open public page": "เปิดหน้าจองสาธารณะ",
  "Preview availability": "ดูตัวอย่างเวลาที่จองได้",
  "No booking links yet. Create the first consultation link above.": "ยังไม่มีลิงก์จอง สร้างลิงก์นัดปรึกษารายการแรกด้านบน",
  "Link name": "ชื่อลิงก์",
  "Title": "ชื่อเรื่อง",
  "Description": "คำอธิบาย",
  "Meeting location": "สถานที่นัดหมาย",
  "Duration minutes": "ระยะเวลา (นาที)",
  "Minimum notice": "เวลาจองล่วงหน้าอย่างน้อย",
  "Booking window": "ช่วงวันที่เปิดให้จอง",
  "Max bookings per day": "จำนวนจองสูงสุดต่อวัน",
  "Buffer before": "เวลาพักก่อนนัด",
  "Buffer after": "เวลาพักหลังนัด",
  "Google Meet, Zoom, phone call, or office location": "Google Meet, Zoom, โทรศัพท์ หรือสถานที่สำนักงาน",
  "Short customer-facing note for this booking link.": "คำอธิบายสั้น ๆ ที่ลูกค้าจะเห็นบนหน้าจอง",
  "Set open appointment hours, block busy time, and preview real slots for booking links.": "กำหนดเวลารับนัด ปิดช่วงที่ไม่ว่าง และดูตัวอย่างเวลาจริงสำหรับลิงก์จอง",
  "Switch admin": "เปลี่ยนผู้ดูแล",
  "Preview link": "ดูตัวอย่างลิงก์",
  "Add block or extra time": "เพิ่มช่วงไม่ว่างหรือช่วงเปิดพิเศษ",
  "Add override": "เพิ่มข้อยกเว้นเวลา",
  "Blocked time": "ช่วงเวลาที่ไม่ว่าง",
  "Extra available": "เปิดรับนัดเป็นกรณีพิเศษ",
  "Extra available time": "ช่วงเปิดรับนัดพิเศษ",
  "Holiday, client visit, extra opening...": "วันหยุด พบลูกค้า หรือเปิดรับนัดพิเศษ...",
  "Upcoming overrides": "ข้อยกเว้นเวลาที่กำลังจะมาถึง",
  "Upcoming blocked and extra time": "ช่วงไม่ว่างและช่วงเปิดพิเศษที่กำลังจะมาถึง",
  "No upcoming overrides.": "ไม่มีข้อยกเว้นเวลาที่กำลังจะมาถึง",
  "No available slots in the next 14 days. Check weekly hours, blocks, booking-window, minimum notice, and active status.": "ไม่มีเวลาว่างใน 14 วันข้างหน้า โปรดตรวจเวลารายสัปดาห์ ช่วงไม่ว่าง ระยะเปิดจอง เวลาจองล่วงหน้า และสถานะการใช้งาน",
  "Appointments": "นัดหมาย",
  "Search appointments": "ค้นหานัดหมาย",
  "Appointment list": "รายการนัดหมาย",
  "Appointment notes": "บันทึกนัดหมาย",
  "No appointments in this view.": "ไม่มีนัดหมายในมุมมองนี้",
  "No calendar items in this view.": "ไม่มีรายการปฏิทินในมุมมองนี้",
  "No events.": "ไม่มีกิจกรรม",
  "Conversation": "การสนทนา",
  "Back to appointments": "กลับไปหน้ารายการนัดหมาย",
  "Cancel": "ยกเลิก",
  "Reassign to...": "มอบหมายให้...",
  "Status": "สถานะ",
  "Status:": "สถานะ:",
  "Type": "ประเภท",
  "Starts": "เริ่ม",
  "Ends": "สิ้นสุด",
  "Reason": "เหตุผล",
  "Upcoming:": "รายการที่กำลังจะมาถึง:",
  "Settings updated.": "อัปเดตการตั้งค่าแล้ว",
  "Settings saved. Knowledge version": "บันทึกการตั้งค่าแล้ว คลังความรู้เวอร์ชัน",
  "applies to new sessions immediately.": "จะมีผลกับการสนทนาใหม่ทันที",
  "Profile": "โปรไฟล์",
  "Name": "ชื่อ",
  "Change password": "เปลี่ยนรหัสผ่าน",
  "Current password": "รหัสผ่านปัจจุบัน",
  "New password": "รหัสผ่านใหม่",
  "Confirm new password": "ยืนยันรหัสผ่านใหม่",
  "Update password": "อัปเดตรหัสผ่าน",
  "Voice agent": "ผู้ช่วยเสียง",
  "Live-call availability, greeting, language, and call limits.": "ตั้งค่าการเปิดรับสาย คำทักทาย ภาษา และระยะเวลาสนทนา",
  "Agent enabled": "เปิดใช้งานผู้ช่วย",
  "Greeting": "คำทักทาย",
  "Language mode": "รูปแบบภาษา",
  "Max call seconds": "ระยะเวลาสนทนาสูงสุด (วินาที)",
  "Daily session cap": "จำนวนการสนทนาสูงสุดต่อวัน",
  "Booking": "การจอง",
  "Controls the public booking page and the voice-widget booking CTA.": "ควบคุมหน้าจองสาธารณะและปุ่มจองในวิดเจ็ตเสียง",
  "Require admin confirmation": "ต้องให้ผู้ดูแลยืนยัน",
  "Post-call analysis": "การวิเคราะห์หลังจบการสนทนา",
  "Summary, lead extraction, interest level, objections, and next action.": "สรุปการสนทนา ดึงข้อมูลผู้สนใจ ประเมินความสนใจ ข้อกังวล และขั้นตอนถัดไป",
  "Analysis enabled": "เปิดใช้งานการวิเคราะห์",
  "Analysis model": "โมเดลวิเคราะห์",
  "Text Chatbot": "แชตบอตข้อความ",
  "Chatbot enabled": "เปิดใช้งานแชตบอต",
  "Daily text session cap": "จำนวนแชตสูงสุดต่อวัน",
  "Max messages/session": "จำนวนข้อความสูงสุดต่อการสนทนา",
  "Text chatbot uses the same sales behavior and knowledge document as the voice agent.": "แชตบอตใช้แนวทางการขายและคลังความรู้เดียวกับผู้ช่วยเสียง",
  "Knowledge document": "คลังความรู้",
  "The voice agent may only state facts that appear here.": "ผู้ช่วย AI แจ้งข้อมูลได้เฉพาะข้อเท็จจริงที่ระบุไว้ที่นี่",
  "Advanced voice provider": "การตั้งค่าผู้ให้บริการเสียงขั้นสูง",
  "Switch between OpenAI Realtime and Gemini Live without redeploying.": "สลับระหว่าง OpenAI Realtime และ Gemini Live ได้โดยไม่ต้องติดตั้งระบบใหม่",
  "Voice provider": "ผู้ให้บริการเสียง",
  "Live model ID": "รหัสโมเดลสนทนาสด",
  "Transcription model": "โมเดลถอดเสียง",
  "Save settings": "บันทึกการตั้งค่า",
  "Manage settings": "จัดการการตั้งค่า",
  "Team settings updated.": "อัปเดตการตั้งค่าทีมแล้ว",
  "Create admins, manage roles, and review calendar ownership.": "สร้างผู้ดูแล จัดการบทบาท และตรวจสอบเจ้าของปฏิทิน",
  "Create admin": "สร้างผู้ดูแล",
  "Admins": "ผู้ดูแล",
  "Role": "บทบาท",
  "Temp password": "รหัสผ่านชั่วคราว",
  "Active account": "บัญชีที่ใช้งานอยู่",
  "Allow self-edit": "อนุญาตให้แก้ไขบัญชีตนเอง",
  "Save admin": "บันทึกผู้ดูแล",
  "Delete admin": "ลบผู้ดูแล",
  "Deactivate": "ปิดใช้งาน",
  "Editing admin": "กำลังแก้ไขผู้ดูแล",
  "No admin accounts found.": "ไม่พบบัญชีผู้ดูแล",
  "Last login:": "เข้าสู่ระบบล่าสุด:",
  "Search conversations": "ค้นหาการสนทนา",
  "Conversation intelligence": "ข้อมูลวิเคราะห์การสนทนา",
  "Summary": "สรุป",
  "Interest level": "ระดับความสนใจ",
  "Concern or objection": "ข้อกังวลหรือข้อโต้แย้ง",
  "Next action": "ขั้นตอนถัดไป",
  "Save analysis": "บันทึกผลวิเคราะห์",
  "No conversation selected": "ยังไม่ได้เลือกการสนทนา",
  "Choose a voice conversation from the list.": "เลือกการสนทนาด้วยเสียงจากรายการ",
  "Customer and lead": "ลูกค้าและข้อมูลผู้สนใจ",
  "No lead captured": "ไม่พบข้อมูลผู้สนใจ",
  "This conversation remains in the no-lead view unless contact details are found later.": "การสนทนานี้จะอยู่ในรายการที่ไม่มีข้อมูลผู้สนใจ จนกว่าจะพบช่องทางติดต่อในภายหลัง",
  "No linked appointments.": "ไม่มีนัดหมายที่เชื่อมโยง",
  "Admin actions": "การดำเนินการของผู้ดูแล",
  "Select a conversation to view customer, lead, appointment, and notes.": "เลือกการสนทนาเพื่อดูข้อมูลลูกค้า ผู้สนใจ นัดหมาย และบันทึก",
  "No conversations in this view.": "ไม่มีการสนทนาในมุมมองนี้",
  "No transcript saved.": "ไม่มีข้อความถอดเสียงที่บันทึกไว้",
  "Star": "ติดดาว",
  "Reanalyse": "วิเคราะห์ใหม่",
  "Delete conversation": "ลบการสนทนา",
  "Conversation analysis refreshed.": "วิเคราะห์การสนทนาใหม่แล้ว",
  "Conversation deleted.": "ลบการสนทนาแล้ว",
  "Open in Inbox": "เปิดในกล่องข้อความ",
  "Open detail page": "เปิดหน้ารายละเอียด",
  "Export CSV": "ส่งออก CSV",
  "Save": "บันทึก",
  "Delete": "ลบ",
  "Reset": "ล้างค่า",
  "Create": "สร้าง",
  "Notice": "ระยะเวลาจองล่วงหน้า",
  "Duration": "ระยะเวลา",
  "Timezone": "เขตเวลา",
  "Owner admin": "ผู้ดูแลเจ้าของลิงก์",
  "Public slug": "ชื่อท้ายลิงก์สาธารณะ",
  "Require confirmation": "ต้องยืนยันการจอง",
  "Max/day": "สูงสุด/วัน",
  "Min notice": "จองล่วงหน้าอย่างน้อย",
  "Booking window days": "จำนวนวันที่เปิดให้จอง",
  "Max bookings/day": "จำนวนจองสูงสุด/วัน",
  "Slot preview": "ตัวอย่างเวลาที่จองได้",
  "Slot preview link": "ลิงก์ดูตัวอย่างเวลาจอง",
  "Appointment:": "นัดหมาย:",
  "Booking link:": "ลิงก์จอง:",
  "Calendar:": "ปฏิทิน:",
  "Assigned:": "มอบหมายให้:",
  "Pending:": "รอดำเนินการ:",
  "Interest:": "ระดับความสนใจ:",
  "Concern:": "ข้อกังวล:",
  "Next:": "ขั้นตอนถัดไป:",
  "Phone:": "โทรศัพท์:",
  "Email:": "อีเมล:",
  "LINE:": "LINE:",
  "WhatsApp:": "WhatsApp:",
  "Last activity:": "ใช้งานล่าสุด:",
  "Last seen:": "พบล่าสุด:",
  "Deleted": "ลบแล้ว",
};

const AMBIGUOUS_CUSTOMER_VALUES = new Set(["Contact", "No", "Yes", "Unknown", "unknown"]);

function chosenLocale(): Locale {
  const query = new URLSearchParams(window.location.search).get("lang");
  if (query === "th" || query === "en") return query;
  if (/(?:^|;\s*)djay-locale=en(?:;|$)/.test(document.cookie)) return "en";
  return window.localStorage.getItem("djai-admin-locale") === "en" ? "en" : "th";
}

export function translateAdminText(value: string) {
  const trimmed = value.trim();
  if (!trimmed) return value;
  if (AMBIGUOUS_CUSTOMER_VALUES.has(trimmed)) return value;
  let translated: string | undefined = THAI[trimmed];
  if (!translated) {
    const minute = trimmed.match(/^(\d+) minutes?$/);
    const version = trimmed.match(/^Version (\d+)$/);
    if (minute) translated = `${minute[1]} นาที`;
    if (version) translated = `เวอร์ชัน ${version[1]}`;
  }
  if (!translated) return value;
  return `${value.slice(0, value.indexOf(trimmed))}${translated}${value.slice(value.indexOf(trimmed) + trimmed.length)}`;
}

function localize(root: HTMLElement) {
  if (root.closest("[data-no-localize]")) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent || parent.closest("[data-no-localize],script,style,code,pre,textarea,input,select,option")) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    },
  });
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  for (const node of nodes) node.nodeValue = translateAdminText(node.nodeValue || "");
  for (const element of root.querySelectorAll<HTMLElement>("[placeholder], [aria-label], [title]")) {
    if (element.closest("[data-no-localize]")) continue;
    for (const attribute of ["placeholder", "aria-label", "title"] as const) {
      const value = element.getAttribute(attribute);
      if (value) element.setAttribute(attribute, translateAdminText(value));
    }
  }
}

export function AdminLocalizer({ children }: { children: React.ReactNode }) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [locale, setLocale] = useState<Locale>("th");

  useLayoutEffect(() => {
    const selected = chosenLocale();
    setLocale(selected);
    document.documentElement.lang = selected;
    document.cookie = `djay-locale=${selected}; path=/; max-age=31536000; samesite=lax`;
    // Root admin pages are server-rendered at first paint; keep this one-shot so
    // later customer-entered text is not patched after hydration.
    if (selected === "th" && rootRef.current) localize(rootRef.current);
  }, []);

  function select(next: Locale) {
    window.localStorage.setItem("djai-admin-locale", next);
    document.cookie = `djay-locale=${next}; path=/; max-age=31536000; samesite=lax`;
    window.location.reload();
  }

  return (
    <div ref={rootRef}>
      <div data-no-localize className="fixed bottom-4 right-4 z-[100] flex rounded-full border border-slate-200 bg-white p-1 text-xs font-semibold shadow-lg" aria-label="เลือกภาษา / Select language">
        <button type="button" onClick={() => select("th")} className={`rounded-full px-3 py-2 ${locale === "th" ? "bg-[#0e7c86] text-white" : "text-slate-600"}`}>ไทย</button>
        <button type="button" onClick={() => select("en")} className={`rounded-full px-3 py-2 ${locale === "en" ? "bg-[#0e7c86] text-white" : "text-slate-600"}`}>English</button>
      </div>
      {children}
    </div>
  );
}
