"use client";

import { localeText, usePublicLocale } from "../LocaleBoundary";
import { PublicFooter } from "../PublicFooter";
import { PublicInfoHeader } from "../PublicInfoHeader";

const useCases = [
  { typeTh: "ธุรกิจบริการ", typeEn: "Service businesses", titleTh: "คัดกรองผู้สนใจก่อนให้ทีมโทรกลับ", titleEn: "Qualify enquiries before your team calls back", situationTh: "ลูกค้าต้องการทราบราคาและความเหมาะสมของบริการ แต่ทีมยังไม่พร้อมตอบทันที", situationEn: "A customer wants pricing and service-fit information before your team is available.", handlesTh: "ตอบคำถามเบื้องต้น ถามบริการที่สนใจ งบประมาณ ช่วงเวลา และข้อมูลติดต่อ", handlesEn: "Answer initial questions and ask about service interest, budget, timing and contact details.", outcomeTh: "ทีมได้รับลีดพร้อมบริบทสำหรับโทรกลับหรือเสนอขั้นตอนถัดไป", outcomeEn: "Your team receives a lead with context for a callback or next-step recommendation.", products: "Flow Bot · AI Text Bot" },
  { typeTh: "ธุรกิจนัดหมาย", typeEn: "Appointment businesses", titleTh: "พาลูกค้าไปสู่คำขอนัดหมาย", titleEn: "Guide customers toward an appointment request", situationTh: "ลูกค้าถามบริการและเวลาว่าง แต่การคุยจบลงโดยไม่มีข้อมูลสำหรับติดตาม", situationEn: "Customers ask about services and availability, but the conversation ends without follow-up details.", handlesTh: "ตอบคำถามบริการ เก็บวันที่หรือช่วงเวลาที่สะดวก และยืนยันข้อมูลติดต่อ", handlesEn: "Answer service questions, collect preferred dates or times and confirm contact details.", outcomeTh: "ทีมได้รับคำขอนัดหมายที่มีข้อมูลพร้อมสำหรับตรวจและยืนยัน", outcomeEn: "Your team receives a structured appointment request ready for review and confirmation.", products: "Flow Bot · AI Text Bot · AI Voice Bot" },
  { typeTh: "ร้านค้าและธุรกิจท้องถิ่น", typeEn: "Retail and local businesses", titleTh: "ตอบคำถามซ้ำและส่งต่อเมื่อจำเป็น", titleEn: "Handle repetitive questions and hand off when needed", situationTh: "ทีมใช้เวลาตอบเรื่องสินค้า บริการ เวลาเปิด และสถานที่ซ้ำตลอดวัน", situationEn: "Your team repeatedly answers questions about products, services, opening hours and location.", handlesTh: "ให้คำตอบที่อนุมัติแล้ว แนะนำหัวข้อที่เกี่ยวข้อง และเสนอช่องทางติดต่อคน", handlesEn: "Provide approved answers, suggest relevant topics and offer a route to a person.", outcomeTh: "ลูกค้าได้คำตอบสม่ำเสมอ ขณะที่ทีมรับเฉพาะบทสนทนาที่ต้องใช้คน", outcomeEn: "Customers receive consistent information while your team handles conversations that need a person.", products: "Flow Bot · AI Text Bot" },
  { typeTh: "ที่ปรึกษาและเอเจนซี", typeEn: "Consultants and agencies", titleTh: "เก็บโจทย์ก่อนเริ่มการสนทนาขาย", titleEn: "Capture the brief before a sales conversation", situationTh: "การประชุมแรกเสียเวลาไปกับการถามข้อมูลพื้นฐานที่สามารถเก็บล่วงหน้าได้", situationEn: "The first meeting is spent collecting basic information that could have been gathered earlier.", handlesTh: "ถามเป้าหมาย ปัญหา ขอบเขตงาน ระยะเวลา และผู้มีอำนาจตัดสินใจ", handlesEn: "Ask about goals, challenges, scope, timing and decision-making context.", outcomeTh: "ทีมเข้าสู่การคุยพร้อมโจทย์ที่ชัดขึ้นและเตรียมคำแนะนำได้ตรงกว่าเดิม", outcomeEn: "Your team enters the conversation with a clearer brief and better preparation.", products: "AI Text Bot · AI Voice Bot" },
] as const;

export default function TemplatesPage() {
  const { locale } = usePublicLocale();
  const t = (th: string, en: string) => localeText(locale, th, en);
  return <main className="info-page" id="main-content"><PublicInfoHeader />
    <section className="info-hero use-case-hero"><p>{t("ตัวอย่างการใช้งาน", "USE CASES")}</p><h1>{t("เริ่มจากสิ่งที่ธุรกิจต้องการให้เกิดขึ้น", "Start with the outcome your business needs")}</h1><span>{t("แต่ละตัวอย่างอธิบายปัญหาของลูกค้า งานที่ Bot รับผิดชอบ ข้อมูลที่เก็บ และขั้นตอนที่ทีมต้องทำต่อ ไม่ใช่บทความหรือเทมเพลตเปล่า", "Each use case explains the customer problem, the bot's job, the information captured and the action your team takes next.")}</span></section>
    <section className="info-content use-case-content"><div className="use-case-filter" aria-label={t("เลือกตามเป้าหมาย", "Choose by goal")}><span>{t("เป้าหมายที่รองรับ", "Supported goals")}</span><strong>{t("ตอบคำถาม", "Answer questions")}</strong><strong>{t("เก็บลีด", "Capture leads")}</strong><strong>{t("ขอนัดหมาย", "Request appointments")}</strong><strong>{t("ส่งต่อทีม", "Hand off to a team")}</strong></div>
      <div className="use-case-list">{useCases.map((item) => <article key={item.titleTh}><div className="use-case-label">{t(item.typeTh, item.typeEn)}</div><div className="use-case-main"><h2>{t(item.titleTh, item.titleEn)}</h2><p>{t(item.situationTh, item.situationEn)}</p></div><dl><div><dt>{t("Bot ช่วยทำอะไร", "What the bot handles")}</dt><dd>{t(item.handlesTh, item.handlesEn)}</dd></div><div><dt>{t("ทีมได้รับอะไร", "What your team receives")}</dt><dd>{t(item.outcomeTh, item.outcomeEn)}</dd></div><div><dt>{t("ใช้กับ", "Available with")}</dt><dd>{item.products}</dd></div></dl><a href="/pricing">{t("ดูแพ็กเกจที่เกี่ยวข้อง", "View relevant packages")} <span aria-hidden="true">→</span></a></article>)}</div>
      <section className="use-case-cta"><div><p>{t("พร้อมเลือกวิธีเริ่มต้น", "READY TO CHOOSE A STARTING POINT?")}</p><h2>{t("เปรียบเทียบ Bot และแพ็กเกจตามงานที่ต้องการ", "Compare bots and packages by the job you need done")}</h2></div><a className="primary-link" href="/pricing">{t("ดูแพ็กเกจ", "View packages")}</a></section>
    </section><PublicFooter />
  </main>;
}
